// Auto-generated by scripts/generate-seed-fits.test.ts — do not edit by hand.
// Produced by the deterministic Skill Intelligence Graph engine from seed-data.ts.
import type { FitRecord } from "./skill-graph-engine.ts";

export const SEED_FITS: Record<string, FitRecord[]> = {
  "22222222-2222-2222-2222-222222222203": [
    {
      "target_type": "requisition",
      "target_id": "33333333-3333-3333-3333-333333333301",
      "target_title": "Senior Backend Engineer",
      "scenario": "current",
      "score": 0.392,
      "sections": {
        "direct": {
          "value": 0.354,
          "items": [
            {
              "skill": "Go",
              "classification": "direct",
              "required_proficiency": 4,
              "candidate_proficiency": 3,
              "edge": null,
              "contribution": 0.75,
              "reason": "Holds Go at 3/4 — below the required bar."
            },
            {
              "skill": "Docker",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 2,
              "edge": null,
              "contribution": 0.6666666666666666,
              "reason": "Holds Docker at 2/3 — below the required bar."
            }
          ]
        },
        "adjacent": {
          "value": 0.18,
          "items": [
            {
              "skill": "REST APIs",
              "classification": "adjacent",
              "required_proficiency": 3,
              "candidate_proficiency": null,
              "edge": {
                "from_skill": "Go",
                "type": "ADJACENT_TO",
                "weight": 0.6
              },
              "contribution": 0.36,
              "reason": "No direct REST APIs; backed by Go → REST APIs (ADJACENT_TO, 0.60)."
            }
          ]
        },
        "evidence": {
          "value": 0.6,
          "artifact_count": 3,
          "threshold": 5
        },
        "seniority": {
          "value": 0.8,
          "candidate_level": 3,
          "role_level": 4
        }
      },
      "classification": {
        "direct": [
          {
            "skill": "Go",
            "classification": "direct",
            "required_proficiency": 4,
            "candidate_proficiency": 3,
            "edge": null,
            "contribution": 0.75,
            "reason": "Holds Go at 3/4 — below the required bar."
          },
          {
            "skill": "Docker",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 2,
            "edge": null,
            "contribution": 0.6666666666666666,
            "reason": "Holds Docker at 2/3 — below the required bar."
          }
        ],
        "adjacent": [
          {
            "skill": "REST APIs",
            "classification": "adjacent",
            "required_proficiency": 3,
            "candidate_proficiency": null,
            "edge": {
              "from_skill": "Go",
              "type": "ADJACENT_TO",
              "weight": 0.6
            },
            "contribution": 0.36,
            "reason": "No direct REST APIs; backed by Go → REST APIs (ADJACENT_TO, 0.60)."
          }
        ],
        "transferable": [
          {
            "skill": "PostgreSQL",
            "classification": "transferable",
            "required_proficiency": 3,
            "candidate_proficiency": null,
            "edge": null,
            "contribution": null,
            "reason": "No direct or adjacent path; SQL shares the same category (Data)."
          }
        ],
        "gaps": []
      },
      "computed_at": "2026-09-15T09:00:00Z"
    },
    {
      "target_type": "requisition",
      "target_id": "33333333-3333-3333-3333-333333333301",
      "target_title": "Senior Backend Engineer",
      "scenario": "future",
      "score": 0.17,
      "sections": {
        "direct": {
          "value": 0,
          "items": []
        },
        "adjacent": {
          "value": 0,
          "items": []
        },
        "evidence": {
          "value": 0.6,
          "artifact_count": 3,
          "threshold": 5
        },
        "seniority": {
          "value": 0.8,
          "candidate_level": 3,
          "role_level": 4
        }
      },
      "classification": {
        "direct": [],
        "adjacent": [],
        "transferable": [
          {
            "skill": "Kubernetes",
            "classification": "transferable",
            "required_proficiency": 2,
            "candidate_proficiency": null,
            "edge": null,
            "contribution": null,
            "reason": "No direct or adjacent path; Docker shares the same category (DevOps)."
          }
        ],
        "gaps": [
          {
            "skill": "Event-driven architecture",
            "classification": "gap",
            "required_proficiency": 2,
            "candidate_proficiency": null,
            "edge": null,
            "contribution": null,
            "reason": "No direct, adjacent, or transferable path found for Event-driven architecture."
          }
        ]
      },
      "computed_at": "2026-09-15T09:00:00Z"
    }
  ],
  "22222222-2222-2222-2222-222222222204": [
    {
      "target_type": "requisition",
      "target_id": "33333333-3333-3333-3333-333333333302",
      "target_title": "Data Analyst",
      "scenario": "current",
      "score": 0.898,
      "sections": {
        "direct": {
          "value": 0.917,
          "items": [
            {
              "skill": "SQL",
              "classification": "direct",
              "required_proficiency": 4,
              "candidate_proficiency": 4,
              "edge": null,
              "contribution": 1,
              "reason": "Holds SQL at 4/4 required."
            },
            {
              "skill": "Python",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 3,
              "edge": null,
              "contribution": 1,
              "reason": "Holds Python at 3/3 required."
            },
            {
              "skill": "Data Modeling",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 2,
              "edge": null,
              "contribution": 0.6666666666666666,
              "reason": "Holds Data Modeling at 2/3 — below the required bar."
            },
            {
              "skill": "Tableau",
              "classification": "direct",
              "required_proficiency": 2,
              "candidate_proficiency": 3,
              "edge": null,
              "contribution": 1,
              "reason": "Holds Tableau at 3/2 required."
            }
          ]
        },
        "adjacent": {
          "value": 1,
          "items": []
        },
        "evidence": {
          "value": 0.6,
          "artifact_count": 3,
          "threshold": 5
        },
        "seniority": {
          "value": 1,
          "candidate_level": 3,
          "role_level": 3
        }
      },
      "classification": {
        "direct": [
          {
            "skill": "SQL",
            "classification": "direct",
            "required_proficiency": 4,
            "candidate_proficiency": 4,
            "edge": null,
            "contribution": 1,
            "reason": "Holds SQL at 4/4 required."
          },
          {
            "skill": "Python",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 3,
            "edge": null,
            "contribution": 1,
            "reason": "Holds Python at 3/3 required."
          },
          {
            "skill": "Data Modeling",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 2,
            "edge": null,
            "contribution": 0.6666666666666666,
            "reason": "Holds Data Modeling at 2/3 — below the required bar."
          },
          {
            "skill": "Tableau",
            "classification": "direct",
            "required_proficiency": 2,
            "candidate_proficiency": 3,
            "edge": null,
            "contribution": 1,
            "reason": "Holds Tableau at 3/2 required."
          }
        ],
        "adjacent": [],
        "transferable": [],
        "gaps": []
      },
      "computed_at": "2026-09-15T09:00:00Z"
    }
  ],
  "22222222-2222-2222-2222-222222222205": [
    {
      "target_type": "requisition",
      "target_id": "33333333-3333-3333-3333-333333333301",
      "target_title": "Senior Backend Engineer",
      "scenario": "current",
      "score": 0.655,
      "sections": {
        "direct": {
          "value": 0.75,
          "items": [
            {
              "skill": "Go",
              "classification": "direct",
              "required_proficiency": 4,
              "candidate_proficiency": 4,
              "edge": null,
              "contribution": 1,
              "reason": "Holds Go at 4/4 required."
            },
            {
              "skill": "PostgreSQL",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 4,
              "edge": null,
              "contribution": 1,
              "reason": "Holds PostgreSQL at 4/3 required."
            },
            {
              "skill": "Docker",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 3,
              "edge": null,
              "contribution": 1,
              "reason": "Holds Docker at 3/3 required."
            }
          ]
        },
        "adjacent": {
          "value": 0.48,
          "items": [
            {
              "skill": "REST APIs",
              "classification": "adjacent",
              "required_proficiency": 3,
              "candidate_proficiency": null,
              "edge": {
                "from_skill": "Go",
                "type": "ADJACENT_TO",
                "weight": 0.6
              },
              "contribution": 0.48,
              "reason": "No direct REST APIs; backed by Go → REST APIs (ADJACENT_TO, 0.60)."
            }
          ]
        },
        "evidence": {
          "value": 0.4,
          "artifact_count": 2,
          "threshold": 5
        },
        "seniority": {
          "value": 1,
          "candidate_level": 4,
          "role_level": 4
        }
      },
      "classification": {
        "direct": [
          {
            "skill": "Go",
            "classification": "direct",
            "required_proficiency": 4,
            "candidate_proficiency": 4,
            "edge": null,
            "contribution": 1,
            "reason": "Holds Go at 4/4 required."
          },
          {
            "skill": "PostgreSQL",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 4,
            "edge": null,
            "contribution": 1,
            "reason": "Holds PostgreSQL at 4/3 required."
          },
          {
            "skill": "Docker",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 3,
            "edge": null,
            "contribution": 1,
            "reason": "Holds Docker at 3/3 required."
          }
        ],
        "adjacent": [
          {
            "skill": "REST APIs",
            "classification": "adjacent",
            "required_proficiency": 3,
            "candidate_proficiency": null,
            "edge": {
              "from_skill": "Go",
              "type": "ADJACENT_TO",
              "weight": 0.6
            },
            "contribution": 0.48,
            "reason": "No direct REST APIs; backed by Go → REST APIs (ADJACENT_TO, 0.60)."
          }
        ],
        "transferable": [],
        "gaps": []
      },
      "computed_at": "2026-09-15T09:00:00Z"
    }
  ],
  "22222222-2222-2222-2222-222222222206": [
    {
      "target_type": "requisition",
      "target_id": "33333333-3333-3333-3333-333333333301",
      "target_title": "Senior Backend Engineer",
      "scenario": "current",
      "score": 0.248,
      "sections": {
        "direct": {
          "value": 0.375,
          "items": [
            {
              "skill": "Go",
              "classification": "direct",
              "required_proficiency": 4,
              "candidate_proficiency": 2,
              "edge": null,
              "contribution": 0.5,
              "reason": "Holds Go at 2/4 — below the required bar."
            },
            {
              "skill": "REST APIs",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 3,
              "edge": null,
              "contribution": 1,
              "reason": "Holds REST APIs at 3/3 required."
            }
          ]
        },
        "adjacent": {
          "value": 0,
          "items": []
        },
        "evidence": {
          "value": 0,
          "artifact_count": 0,
          "threshold": 5
        },
        "seniority": {
          "value": 0.6,
          "candidate_level": 2,
          "role_level": 4
        }
      },
      "classification": {
        "direct": [
          {
            "skill": "Go",
            "classification": "direct",
            "required_proficiency": 4,
            "candidate_proficiency": 2,
            "edge": null,
            "contribution": 0.5,
            "reason": "Holds Go at 2/4 — below the required bar."
          },
          {
            "skill": "REST APIs",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 3,
            "edge": null,
            "contribution": 1,
            "reason": "Holds REST APIs at 3/3 required."
          }
        ],
        "adjacent": [],
        "transferable": [],
        "gaps": [
          {
            "skill": "PostgreSQL",
            "classification": "gap",
            "required_proficiency": 3,
            "candidate_proficiency": null,
            "edge": null,
            "contribution": null,
            "reason": "No direct, adjacent, or transferable path found for PostgreSQL."
          },
          {
            "skill": "Docker",
            "classification": "gap",
            "required_proficiency": 3,
            "candidate_proficiency": null,
            "edge": null,
            "contribution": null,
            "reason": "No direct, adjacent, or transferable path found for Docker."
          }
        ]
      },
      "computed_at": "2026-09-15T09:00:00Z"
    }
  ],
  "22222222-2222-2222-2222-222222222207": [
    {
      "target_type": "requisition",
      "target_id": "33333333-3333-3333-3333-333333333302",
      "target_title": "Data Analyst",
      "scenario": "current",
      "score": 0.83,
      "sections": {
        "direct": {
          "value": 1,
          "items": [
            {
              "skill": "SQL",
              "classification": "direct",
              "required_proficiency": 4,
              "candidate_proficiency": 4,
              "edge": null,
              "contribution": 1,
              "reason": "Holds SQL at 4/4 required."
            },
            {
              "skill": "Python",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 3,
              "edge": null,
              "contribution": 1,
              "reason": "Holds Python at 3/3 required."
            },
            {
              "skill": "Data Modeling",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 3,
              "edge": null,
              "contribution": 1,
              "reason": "Holds Data Modeling at 3/3 required."
            },
            {
              "skill": "Tableau",
              "classification": "direct",
              "required_proficiency": 2,
              "candidate_proficiency": 2,
              "edge": null,
              "contribution": 1,
              "reason": "Holds Tableau at 2/2 required."
            }
          ]
        },
        "adjacent": {
          "value": 1,
          "items": []
        },
        "evidence": {
          "value": 0,
          "artifact_count": 0,
          "threshold": 5
        },
        "seniority": {
          "value": 0.8,
          "candidate_level": 2,
          "role_level": 3
        }
      },
      "classification": {
        "direct": [
          {
            "skill": "SQL",
            "classification": "direct",
            "required_proficiency": 4,
            "candidate_proficiency": 4,
            "edge": null,
            "contribution": 1,
            "reason": "Holds SQL at 4/4 required."
          },
          {
            "skill": "Python",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 3,
            "edge": null,
            "contribution": 1,
            "reason": "Holds Python at 3/3 required."
          },
          {
            "skill": "Data Modeling",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 3,
            "edge": null,
            "contribution": 1,
            "reason": "Holds Data Modeling at 3/3 required."
          },
          {
            "skill": "Tableau",
            "classification": "direct",
            "required_proficiency": 2,
            "candidate_proficiency": 2,
            "edge": null,
            "contribution": 1,
            "reason": "Holds Tableau at 2/2 required."
          }
        ],
        "adjacent": [],
        "transferable": [],
        "gaps": []
      },
      "computed_at": "2026-09-15T09:00:00Z"
    }
  ]
};
