// Auto-generated by scripts/generate-seed-fits.test.ts — do not edit by hand.
// Produced by the deterministic Skill Intelligence Graph engine from seed-data.ts.
import type { FitRecord } from "./skill-graph-engine.ts";

export const SEED_FITS: Record<string, FitRecord[]> = {
  "22222222-2222-2222-2222-222222222203": [
    {
      "target_type": "requisition",
      "target_id": "33333333-3333-3333-3333-333333333301",
      "target_title": "Senior Backend Engineer",
      "scenario": "current",
      "score": 0.392,
      "sections": {
        "direct": {
          "value": 0.354,
          "items": [
            {
              "skill": "Go",
              "classification": "direct",
              "required_proficiency": 4,
              "candidate_proficiency": 3,
              "edge": null,
              "contribution": 0.75,
              "reason": "Holds Go at 3/4 — below the required bar.",
              "limitation": null
            },
            {
              "skill": "Docker",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 2,
              "edge": null,
              "contribution": 0.6666666666666666,
              "reason": "Holds Docker at 2/3 — below the required bar.",
              "limitation": null
            }
          ]
        },
        "adjacent": {
          "value": 0.18,
          "items": [
            {
              "skill": "REST APIs",
              "classification": "adjacent",
              "required_proficiency": 3,
              "candidate_proficiency": null,
              "edge": {
                "from_skill": "Go",
                "type": "ADJACENT_TO",
                "weight": 0.6
              },
              "contribution": 0.36,
              "reason": "No direct REST APIs; backed by Go → REST APIs (ADJACENT_TO, 0.60).",
              "limitation": "Adjacent support is NOT direct equivalence: this person has no evidence for the required skill itself. Confirm real capability before relying on it."
            }
          ]
        },
        "evidence": {
          "value": 0.6,
          "artifact_count": 3,
          "threshold": 5
        },
        "seniority": {
          "value": 0.8,
          "candidate_level": 3,
          "role_level": 4
        }
      },
      "classification": {
        "direct": [
          {
            "skill": "Go",
            "classification": "direct",
            "required_proficiency": 4,
            "candidate_proficiency": 3,
            "edge": null,
            "contribution": 0.75,
            "reason": "Holds Go at 3/4 — below the required bar.",
            "limitation": null
          },
          {
            "skill": "Docker",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 2,
            "edge": null,
            "contribution": 0.6666666666666666,
            "reason": "Holds Docker at 2/3 — below the required bar.",
            "limitation": null
          }
        ],
        "adjacent": [
          {
            "skill": "REST APIs",
            "classification": "adjacent",
            "required_proficiency": 3,
            "candidate_proficiency": null,
            "edge": {
              "from_skill": "Go",
              "type": "ADJACENT_TO",
              "weight": 0.6
            },
            "contribution": 0.36,
            "reason": "No direct REST APIs; backed by Go → REST APIs (ADJACENT_TO, 0.60).",
            "limitation": "Adjacent support is NOT direct equivalence: this person has no evidence for the required skill itself. Confirm real capability before relying on it."
          }
        ],
        "transferable": [
          {
            "skill": "PostgreSQL",
            "classification": "transferable",
            "required_proficiency": 3,
            "candidate_proficiency": null,
            "edge": null,
            "contribution": null,
            "reason": "No direct or adjacent path; SQL shares the same category (Data).",
            "limitation": "Transferable support is the weakest signal: it does not establish any proficiency in the required skill and contributes no points to the score. Treat it as a development candidate, not capability."
          }
        ],
        "gaps": []
      },
      "versions": {
        "engine": "2",
        "evidence": "9882b815",
        "requisition": "unknown",
        "graph": "8aaab563",
        "context": "c2c73c8e"
      },
      "assumptions": {
        "horizon": "Current",
        "note": "Current requirements — as recorded on the requisition today."
      },
      "computed_at": "2026-09-15T09:00:00Z"
    },
    {
      "target_type": "requisition",
      "target_id": "33333333-3333-3333-3333-333333333301",
      "target_title": "Senior Backend Engineer",
      "scenario": "future",
      "score": 0.311,
      "sections": {
        "direct": {
          "value": 0.236,
          "items": [
            {
              "skill": "Go",
              "classification": "direct",
              "required_proficiency": 4,
              "candidate_proficiency": 3,
              "edge": null,
              "contribution": 0.75,
              "reason": "Holds Go at 3/4 — below the required bar.",
              "limitation": null
            },
            {
              "skill": "Docker",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 2,
              "edge": null,
              "contribution": 0.6666666666666666,
              "reason": "Holds Docker at 2/3 — below the required bar.",
              "limitation": null
            }
          ]
        },
        "adjacent": {
          "value": 0.09,
          "items": [
            {
              "skill": "REST APIs",
              "classification": "adjacent",
              "required_proficiency": 3,
              "candidate_proficiency": null,
              "edge": {
                "from_skill": "Go",
                "type": "ADJACENT_TO",
                "weight": 0.6
              },
              "contribution": 0.36,
              "reason": "No direct REST APIs; backed by Go → REST APIs (ADJACENT_TO, 0.60).",
              "limitation": "Adjacent support is NOT direct equivalence: this person has no evidence for the required skill itself. Confirm real capability before relying on it."
            }
          ]
        },
        "evidence": {
          "value": 0.6,
          "artifact_count": 3,
          "threshold": 5
        },
        "seniority": {
          "value": 0.8,
          "candidate_level": 3,
          "role_level": 4
        }
      },
      "classification": {
        "direct": [
          {
            "skill": "Go",
            "classification": "direct",
            "required_proficiency": 4,
            "candidate_proficiency": 3,
            "edge": null,
            "contribution": 0.75,
            "reason": "Holds Go at 3/4 — below the required bar.",
            "limitation": null
          },
          {
            "skill": "Docker",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 2,
            "edge": null,
            "contribution": 0.6666666666666666,
            "reason": "Holds Docker at 2/3 — below the required bar.",
            "limitation": null
          }
        ],
        "adjacent": [
          {
            "skill": "REST APIs",
            "classification": "adjacent",
            "required_proficiency": 3,
            "candidate_proficiency": null,
            "edge": {
              "from_skill": "Go",
              "type": "ADJACENT_TO",
              "weight": 0.6
            },
            "contribution": 0.36,
            "reason": "No direct REST APIs; backed by Go → REST APIs (ADJACENT_TO, 0.60).",
            "limitation": "Adjacent support is NOT direct equivalence: this person has no evidence for the required skill itself. Confirm real capability before relying on it."
          }
        ],
        "transferable": [
          {
            "skill": "PostgreSQL",
            "classification": "transferable",
            "required_proficiency": 4,
            "candidate_proficiency": null,
            "edge": null,
            "contribution": null,
            "reason": "No direct or adjacent path; SQL shares the same category (Data).",
            "limitation": "Transferable support is the weakest signal: it does not establish any proficiency in the required skill and contributes no points to the score. Treat it as a development candidate, not capability."
          },
          {
            "skill": "Kubernetes",
            "classification": "transferable",
            "required_proficiency": 2,
            "candidate_proficiency": null,
            "edge": null,
            "contribution": null,
            "reason": "No direct or adjacent path; Docker shares the same category (DevOps).",
            "limitation": "Transferable support is the weakest signal: it does not establish any proficiency in the required skill and contributes no points to the score. Treat it as a development candidate, not capability."
          }
        ],
        "gaps": [
          {
            "skill": "Event-driven architecture",
            "classification": "gap",
            "required_proficiency": 2,
            "candidate_proficiency": null,
            "edge": null,
            "contribution": null,
            "reason": "No direct, adjacent, or transferable path found for Event-driven architecture.",
            "limitation": null
          }
        ]
      },
      "versions": {
        "engine": "2",
        "evidence": "9882b815",
        "requisition": "unknown",
        "graph": "8aaab563",
        "context": "c2c73c8e"
      },
      "assumptions": {
        "horizon": "12–24 month outlook",
        "note": "12–24 month outlook — derived from the requisition's future_skills. Assumption: these skills are the expected demand; edit the requisition to change them."
      },
      "computed_at": "2026-09-15T09:00:00Z"
    }
  ],
  "22222222-2222-2222-2222-222222222204": [
    {
      "target_type": "requisition",
      "target_id": "33333333-3333-3333-3333-333333333302",
      "target_title": "Data Analyst",
      "scenario": "current",
      "score": 0.898,
      "sections": {
        "direct": {
          "value": 0.917,
          "items": [
            {
              "skill": "SQL",
              "classification": "direct",
              "required_proficiency": 4,
              "candidate_proficiency": 4,
              "edge": null,
              "contribution": 1,
              "reason": "Holds SQL at 4/4 required.",
              "limitation": null
            },
            {
              "skill": "Python",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 3,
              "edge": null,
              "contribution": 1,
              "reason": "Holds Python at 3/3 required.",
              "limitation": null
            },
            {
              "skill": "Data Modeling",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 2,
              "edge": null,
              "contribution": 0.6666666666666666,
              "reason": "Holds Data Modeling at 2/3 — below the required bar.",
              "limitation": null
            },
            {
              "skill": "Tableau",
              "classification": "direct",
              "required_proficiency": 2,
              "candidate_proficiency": 3,
              "edge": null,
              "contribution": 1,
              "reason": "Holds Tableau at 3/2 required.",
              "limitation": null
            }
          ]
        },
        "adjacent": {
          "value": 1,
          "items": []
        },
        "evidence": {
          "value": 0.6,
          "artifact_count": 3,
          "threshold": 5
        },
        "seniority": {
          "value": 1,
          "candidate_level": 3,
          "role_level": 3
        }
      },
      "classification": {
        "direct": [
          {
            "skill": "SQL",
            "classification": "direct",
            "required_proficiency": 4,
            "candidate_proficiency": 4,
            "edge": null,
            "contribution": 1,
            "reason": "Holds SQL at 4/4 required.",
            "limitation": null
          },
          {
            "skill": "Python",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 3,
            "edge": null,
            "contribution": 1,
            "reason": "Holds Python at 3/3 required.",
            "limitation": null
          },
          {
            "skill": "Data Modeling",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 2,
            "edge": null,
            "contribution": 0.6666666666666666,
            "reason": "Holds Data Modeling at 2/3 — below the required bar.",
            "limitation": null
          },
          {
            "skill": "Tableau",
            "classification": "direct",
            "required_proficiency": 2,
            "candidate_proficiency": 3,
            "edge": null,
            "contribution": 1,
            "reason": "Holds Tableau at 3/2 required.",
            "limitation": null
          }
        ],
        "adjacent": [],
        "transferable": [],
        "gaps": []
      },
      "versions": {
        "engine": "2",
        "evidence": "bc60c95a",
        "requisition": "unknown",
        "graph": "8aaab563",
        "context": "c5c74147"
      },
      "assumptions": {
        "horizon": "Current",
        "note": "Current requirements — as recorded on the requisition today."
      },
      "computed_at": "2026-09-15T09:00:00Z"
    }
  ],
  "22222222-2222-2222-2222-222222222205": [
    {
      "target_type": "requisition",
      "target_id": "33333333-3333-3333-3333-333333333301",
      "target_title": "Senior Backend Engineer",
      "scenario": "current",
      "score": 0.655,
      "sections": {
        "direct": {
          "value": 0.75,
          "items": [
            {
              "skill": "Go",
              "classification": "direct",
              "required_proficiency": 4,
              "candidate_proficiency": 4,
              "edge": null,
              "contribution": 1,
              "reason": "Holds Go at 4/4 required.",
              "limitation": null
            },
            {
              "skill": "PostgreSQL",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 4,
              "edge": null,
              "contribution": 1,
              "reason": "Holds PostgreSQL at 4/3 required.",
              "limitation": null
            },
            {
              "skill": "Docker",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 3,
              "edge": null,
              "contribution": 1,
              "reason": "Holds Docker at 3/3 required.",
              "limitation": null
            }
          ]
        },
        "adjacent": {
          "value": 0.48,
          "items": [
            {
              "skill": "REST APIs",
              "classification": "adjacent",
              "required_proficiency": 3,
              "candidate_proficiency": null,
              "edge": {
                "from_skill": "Go",
                "type": "ADJACENT_TO",
                "weight": 0.6
              },
              "contribution": 0.48,
              "reason": "No direct REST APIs; backed by Go → REST APIs (ADJACENT_TO, 0.60).",
              "limitation": "Adjacent support is NOT direct equivalence: this person has no evidence for the required skill itself. Confirm real capability before relying on it."
            }
          ]
        },
        "evidence": {
          "value": 0.4,
          "artifact_count": 2,
          "threshold": 5
        },
        "seniority": {
          "value": 1,
          "candidate_level": 4,
          "role_level": 4
        }
      },
      "classification": {
        "direct": [
          {
            "skill": "Go",
            "classification": "direct",
            "required_proficiency": 4,
            "candidate_proficiency": 4,
            "edge": null,
            "contribution": 1,
            "reason": "Holds Go at 4/4 required.",
            "limitation": null
          },
          {
            "skill": "PostgreSQL",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 4,
            "edge": null,
            "contribution": 1,
            "reason": "Holds PostgreSQL at 4/3 required.",
            "limitation": null
          },
          {
            "skill": "Docker",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 3,
            "edge": null,
            "contribution": 1,
            "reason": "Holds Docker at 3/3 required.",
            "limitation": null
          }
        ],
        "adjacent": [
          {
            "skill": "REST APIs",
            "classification": "adjacent",
            "required_proficiency": 3,
            "candidate_proficiency": null,
            "edge": {
              "from_skill": "Go",
              "type": "ADJACENT_TO",
              "weight": 0.6
            },
            "contribution": 0.48,
            "reason": "No direct REST APIs; backed by Go → REST APIs (ADJACENT_TO, 0.60).",
            "limitation": "Adjacent support is NOT direct equivalence: this person has no evidence for the required skill itself. Confirm real capability before relying on it."
          }
        ],
        "transferable": [],
        "gaps": []
      },
      "versions": {
        "engine": "2",
        "evidence": "176605a3",
        "requisition": "unknown",
        "graph": "8aaab563",
        "context": "6788a556"
      },
      "assumptions": {
        "horizon": "Current",
        "note": "Current requirements — as recorded on the requisition today."
      },
      "computed_at": "2026-09-15T09:00:00Z"
    }
  ],
  "22222222-2222-2222-2222-222222222206": [
    {
      "target_type": "requisition",
      "target_id": "33333333-3333-3333-3333-333333333301",
      "target_title": "Senior Backend Engineer",
      "scenario": "current",
      "score": 0.248,
      "sections": {
        "direct": {
          "value": 0.375,
          "items": [
            {
              "skill": "Go",
              "classification": "direct",
              "required_proficiency": 4,
              "candidate_proficiency": 2,
              "edge": null,
              "contribution": 0.5,
              "reason": "Holds Go at 2/4 — below the required bar.",
              "limitation": null
            },
            {
              "skill": "REST APIs",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 3,
              "edge": null,
              "contribution": 1,
              "reason": "Holds REST APIs at 3/3 required.",
              "limitation": null
            }
          ]
        },
        "adjacent": {
          "value": 0,
          "items": []
        },
        "evidence": {
          "value": 0,
          "artifact_count": 0,
          "threshold": 5
        },
        "seniority": {
          "value": 0.6,
          "candidate_level": 2,
          "role_level": 4
        }
      },
      "classification": {
        "direct": [
          {
            "skill": "Go",
            "classification": "direct",
            "required_proficiency": 4,
            "candidate_proficiency": 2,
            "edge": null,
            "contribution": 0.5,
            "reason": "Holds Go at 2/4 — below the required bar.",
            "limitation": null
          },
          {
            "skill": "REST APIs",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 3,
            "edge": null,
            "contribution": 1,
            "reason": "Holds REST APIs at 3/3 required.",
            "limitation": null
          }
        ],
        "adjacent": [],
        "transferable": [],
        "gaps": [
          {
            "skill": "PostgreSQL",
            "classification": "gap",
            "required_proficiency": 3,
            "candidate_proficiency": null,
            "edge": null,
            "contribution": null,
            "reason": "No direct, adjacent, or transferable path found for PostgreSQL.",
            "limitation": null
          },
          {
            "skill": "Docker",
            "classification": "gap",
            "required_proficiency": 3,
            "candidate_proficiency": null,
            "edge": null,
            "contribution": null,
            "reason": "No direct, adjacent, or transferable path found for Docker.",
            "limitation": null
          }
        ]
      },
      "versions": {
        "engine": "2",
        "evidence": "50873a41",
        "requisition": "unknown",
        "graph": "8aaab563",
        "context": "a9574bb1"
      },
      "assumptions": {
        "horizon": "Current",
        "note": "Current requirements — as recorded on the requisition today."
      },
      "computed_at": "2026-09-15T09:00:00Z"
    }
  ],
  "22222222-2222-2222-2222-222222222207": [
    {
      "target_type": "requisition",
      "target_id": "33333333-3333-3333-3333-333333333302",
      "target_title": "Data Analyst",
      "scenario": "current",
      "score": 0.83,
      "sections": {
        "direct": {
          "value": 1,
          "items": [
            {
              "skill": "SQL",
              "classification": "direct",
              "required_proficiency": 4,
              "candidate_proficiency": 4,
              "edge": null,
              "contribution": 1,
              "reason": "Holds SQL at 4/4 required.",
              "limitation": null
            },
            {
              "skill": "Python",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 3,
              "edge": null,
              "contribution": 1,
              "reason": "Holds Python at 3/3 required.",
              "limitation": null
            },
            {
              "skill": "Data Modeling",
              "classification": "direct",
              "required_proficiency": 3,
              "candidate_proficiency": 3,
              "edge": null,
              "contribution": 1,
              "reason": "Holds Data Modeling at 3/3 required.",
              "limitation": null
            },
            {
              "skill": "Tableau",
              "classification": "direct",
              "required_proficiency": 2,
              "candidate_proficiency": 2,
              "edge": null,
              "contribution": 1,
              "reason": "Holds Tableau at 2/2 required.",
              "limitation": null
            }
          ]
        },
        "adjacent": {
          "value": 1,
          "items": []
        },
        "evidence": {
          "value": 0,
          "artifact_count": 0,
          "threshold": 5
        },
        "seniority": {
          "value": 0.8,
          "candidate_level": 2,
          "role_level": 3
        }
      },
      "classification": {
        "direct": [
          {
            "skill": "SQL",
            "classification": "direct",
            "required_proficiency": 4,
            "candidate_proficiency": 4,
            "edge": null,
            "contribution": 1,
            "reason": "Holds SQL at 4/4 required.",
            "limitation": null
          },
          {
            "skill": "Python",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 3,
            "edge": null,
            "contribution": 1,
            "reason": "Holds Python at 3/3 required.",
            "limitation": null
          },
          {
            "skill": "Data Modeling",
            "classification": "direct",
            "required_proficiency": 3,
            "candidate_proficiency": 3,
            "edge": null,
            "contribution": 1,
            "reason": "Holds Data Modeling at 3/3 required.",
            "limitation": null
          },
          {
            "skill": "Tableau",
            "classification": "direct",
            "required_proficiency": 2,
            "candidate_proficiency": 2,
            "edge": null,
            "contribution": 1,
            "reason": "Holds Tableau at 2/2 required.",
            "limitation": null
          }
        ],
        "adjacent": [],
        "transferable": [],
        "gaps": []
      },
      "versions": {
        "engine": "2",
        "evidence": "ebe00abd",
        "requisition": "unknown",
        "graph": "8aaab563",
        "context": "aa574d44"
      },
      "assumptions": {
        "horizon": "Current",
        "note": "Current requirements — as recorded on the requisition today."
      },
      "computed_at": "2026-09-15T09:00:00Z"
    }
  ]
};
