// Auto-generated by scripts/generate-seed-journey.test.ts — do not edit by hand.
// Produced by the deterministic Kahn onboarding engine from seed-data.ts.
import type { ScheduledTask } from "./onboarding-engine.ts";

export const SEED_JOURNEY_TASKS: ScheduledTask[] = [
  {
    "id": "it",
    "title": "IT & Laptop Provisioning",
    "depends_on": [],
    "non_waivable": false,
    "duration_days": 1,
    "waived": false,
    "status": "pending",
    "start_date": "2026-07-21T09:00:00.000Z",
    "end_date": "2026-07-22T09:00:00.000Z",
    "topological_level": 0,
    "blocked": null
  },
  {
    "id": "security",
    "title": "Security & Compliance Training",
    "depends_on": [],
    "non_waivable": true,
    "duration_days": 1,
    "waived": false,
    "status": "pending",
    "start_date": "2026-07-21T09:00:00.000Z",
    "end_date": "2026-07-22T09:00:00.000Z",
    "topological_level": 0,
    "blocked": null
  },
  {
    "id": "payroll",
    "title": "Direct Deposit & Payroll Setup",
    "depends_on": [],
    "non_waivable": true,
    "duration_days": 0.5,
    "waived": false,
    "status": "pending",
    "start_date": "2026-07-21T09:00:00.000Z",
    "end_date": "2026-07-21T21:00:00.000Z",
    "topological_level": 0,
    "blocked": null
  },
  {
    "id": "access",
    "title": "System Access & SSO",
    "depends_on": [
      "it",
      "security"
    ],
    "non_waivable": false,
    "duration_days": 0.5,
    "waived": false,
    "status": "pending",
    "start_date": "2026-07-22T09:00:00.000Z",
    "end_date": "2026-07-22T21:00:00.000Z",
    "topological_level": 1,
    "blocked": null
  },
  {
    "id": "compliance_signoff",
    "title": "Compliance Sign-off",
    "depends_on": [
      "security"
    ],
    "non_waivable": true,
    "duration_days": 0.5,
    "waived": false,
    "status": "pending",
    "start_date": "2026-07-22T09:00:00.000Z",
    "end_date": "2026-07-22T21:00:00.000Z",
    "topological_level": 1,
    "blocked": null
  },
  {
    "id": "team_intro",
    "title": "Team Introduction & Codebase Walkthrough",
    "depends_on": [
      "access"
    ],
    "non_waivable": false,
    "duration_days": 1,
    "waived": false,
    "status": "pending",
    "start_date": "2026-07-22T21:00:00.000Z",
    "end_date": "2026-07-23T21:00:00.000Z",
    "topological_level": 2,
    "blocked": null
  },
  {
    "id": "skill_go",
    "title": "First contribution using Go",
    "depends_on": [
      "team_intro"
    ],
    "skill": "Go",
    "target_proficiency": 4,
    "non_waivable": false,
    "duration_days": 1,
    "waived": false,
    "status": "pending",
    "start_date": "2026-07-23T21:00:00.000Z",
    "end_date": "2026-07-24T21:00:00.000Z",
    "topological_level": 3,
    "blocked": null
  },
  {
    "id": "skill_postgresql",
    "title": "First contribution using PostgreSQL",
    "depends_on": [
      "team_intro"
    ],
    "skill": "PostgreSQL",
    "target_proficiency": 3,
    "non_waivable": false,
    "duration_days": 1,
    "waived": false,
    "status": "pending",
    "start_date": "2026-07-23T21:00:00.000Z",
    "end_date": "2026-07-24T21:00:00.000Z",
    "topological_level": 3,
    "blocked": null
  },
  {
    "id": "skill_docker",
    "title": "First contribution using Docker",
    "depends_on": [
      "team_intro"
    ],
    "skill": "Docker",
    "target_proficiency": 3,
    "non_waivable": false,
    "duration_days": 1,
    "waived": false,
    "status": "pending",
    "start_date": "2026-07-23T21:00:00.000Z",
    "end_date": "2026-07-24T21:00:00.000Z",
    "topological_level": 3,
    "blocked": null
  },
  {
    "id": "future_kubernetes",
    "title": "Upskilling plan: Kubernetes",
    "depends_on": [
      "skill_go"
    ],
    "skill": "Kubernetes",
    "target_proficiency": 2,
    "non_waivable": false,
    "duration_days": 1,
    "waived": false,
    "status": "pending",
    "start_date": "2026-07-24T21:00:00.000Z",
    "end_date": "2026-07-25T21:00:00.000Z",
    "topological_level": 4,
    "blocked": null
  },
  {
    "id": "future_event_driven_architecture",
    "title": "Upskilling plan: Event-driven architecture",
    "depends_on": [
      "skill_go"
    ],
    "skill": "Event-driven architecture",
    "target_proficiency": 2,
    "non_waivable": false,
    "duration_days": 1,
    "waived": false,
    "status": "pending",
    "start_date": "2026-07-24T21:00:00.000Z",
    "end_date": "2026-07-25T21:00:00.000Z",
    "topological_level": 4,
    "blocked": null
  },
  {
    "id": "survey",
    "title": "Onboarding Feedback Survey",
    "depends_on": [
      "skill_go"
    ],
    "non_waivable": false,
    "duration_days": 0.5,
    "waived": false,
    "status": "pending",
    "start_date": "2026-07-24T21:00:00.000Z",
    "end_date": "2026-07-25T09:00:00.000Z",
    "topological_level": 4,
    "blocked": null
  }
];
