// GENERATED by scripts/bundle-functions.mjs — do not edit by hand.
// Edit supabase/functions/_shared/* and <fn>/source.ts, then re-run the bundler.

// ---------------------------------------------------------------------------
// WorkSense Skill Intelligence Graph engine — the shared, deterministic core.
// Zero LLM calls. Imported by backend functions (Recruitment, Onboarding,
// Recommendation Hub) — never recomputed per page view; results are persisted
// into the subject's digital_twins.computed_fits[].
// ---------------------------------------------------------------------------

export type VerificationRigor = "low" | "medium" | "high";

export interface SkillClaim {
  name: string;
  proficiency: number;
  evidence_source: string;
  verification_rigor: VerificationRigor;
}

export type EdgeType = "PREREQUISITE_OF" | "ADJACENT_TO" | "TRANSFERABLE_TO";

export interface GraphEdge {
  target_skill: string;
  type: EdgeType;
  weight: number; // 0.0 - 1.0
}

export interface GraphSkill {
  skill: string;
  category: string;
  outgoing_edges: GraphEdge[];
}

export interface RequiredSkill {
  skill: string;
  target_proficiency: number;
}

export type Classification = "direct" | "adjacent" | "transferable" | "gap";

export interface FitItem {
  skill: string;
  classification: Classification;
  required_proficiency: number;
  candidate_proficiency: number | null;
  edge: { from_skill: string; type: EdgeType; weight: number } | null;
  contribution: number | null;
  reason: string;
}

export interface FitRecord {
  target_type: "requisition";
  target_id: string;
  target_title: string;
  scenario: "current" | "future";
  score: number;
  sections: {
    direct: { value: number; items: FitItem[] };
    adjacent: { value: number; items: FitItem[] };
    evidence: { value: number; artifact_count: number; threshold: number };
    seniority: { value: number; candidate_level: number; role_level: number };
  };
  classification: {
    direct: FitItem[];
    adjacent: FitItem[];
    transferable: FitItem[];
    gaps: FitItem[];
  };
  computed_at: string;
}

// Validated weights — do not change.
export const MATCH_WEIGHTS = {
  direct: 0.5,
  adjacent: 0.25,
  evidence: 0.15,
  seniority: 0.1,
} as const;

export const DEFAULT_EVIDENCE_THRESHOLD = 5;

const norm = (s: string) => s.trim().toLowerCase();

export function findEdge(
  skillGraph: GraphSkill[],
  from: string,
  to: string,
  type: EdgeType
): GraphEdge | null {
  const node = skillGraph.find((n) => norm(n.skill) === norm(from));
  const edge = node?.outgoing_edges.find(
    (e) => norm(e.target_skill) === norm(to) && e.type === type
  );
  return edge ?? null;
}

const round3 = (n: number) => Math.round(n * 1000) / 1000;

export function computeFit(params: {
  candidateSkills: SkillClaim[];
  candidateLevel: number;
  requiredSkills: RequiredSkill[];
  roleLevel: number;
  skillGraph: GraphSkill[];
  threshold?: number;
  target: { type: "requisition"; id: string; title: string };
  scenario: "current" | "future";
  computedAt?: string;
}): FitRecord {
  const threshold = params.threshold ?? DEFAULT_EVIDENCE_THRESHOLD;
  const graph = params.skillGraph;

  const directItems: FitItem[] = [];
  const adjacentItems: FitItem[] = [];
  const transferableItems: FitItem[] = [];
  const gapItems: FitItem[] = [];
  const directValues: number[] = [];
  const adjacentValues: number[] = [];

  let ownedCount = 0;
  for (const req of params.requiredSkills) {
    const own = params.candidateSkills.find((s) => norm(s.name) === norm(req.skill));
    const ownProficiency = own?.proficiency ?? 0;

    // S_direct: min(1, candidate/required) across ALL required skills — 0 for
    // skills not owned; partial proficiency still contributes its ratio.
    const ratio = own ? Math.min(1, ownProficiency / req.target_proficiency) : 0;
    directValues.push(ratio);

    if (own) {
      ownedCount++;
      if (ownProficiency >= req.target_proficiency) {
        directItems.push({
          skill: req.skill,
          classification: "direct",
          required_proficiency: req.target_proficiency,
          candidate_proficiency: ownProficiency,
          edge: null,
          contribution: ratio,
          reason: `Holds ${req.skill} at ${ownProficiency}/${req.target_proficiency} required.`,
        });
      } else {
        directItems.push({
          skill: req.skill,
          classification: "direct",
          required_proficiency: req.target_proficiency,
          candidate_proficiency: ownProficiency,
          edge: null,
          contribution: ratio,
          reason: `Holds ${req.skill} at ${ownProficiency}/${req.target_proficiency} — below the required bar.`,
        });
      }
      continue;
    }

    // Adjacent: no direct skill, but a real ADJACENT_TO edge exists (with the
    // candidate's proficiency weighting the edge). Never a direct equivalence.
    let bestAdj: { from: string; edge: GraphEdge; value: number } | null = null;
    for (const claim of params.candidateSkills) {
      const edge = findEdge(graph, claim.name, req.skill, "ADJACENT_TO");
      if (edge) {
        const value = (claim.proficiency / 5) * edge.weight;
        if (!bestAdj || value > bestAdj.value) bestAdj = { from: claim.name, edge, value };
      }
    }
    if (bestAdj) {
      adjacentValues.push(bestAdj.value);
      adjacentItems.push({
        skill: req.skill,
        classification: "adjacent",
        required_proficiency: req.target_proficiency,
        candidate_proficiency: ownProficiency || null,
        edge: { from_skill: bestAdj.from, type: "ADJACENT_TO", weight: bestAdj.edge.weight },
        contribution: bestAdj.value,
        reason: `No direct ${req.skill}; backed by ${bestAdj.from} → ${req.skill} (ADJACENT_TO, ${bestAdj.edge.weight.toFixed(2)}).`,
      });
      continue;
    }

    // Transferable: no direct/adjacent edge, but a TRANSFERABLE_TO edge or a
    // strong same-category relationship exists.
    let transfer: { from: string; edge: GraphEdge | null; via: string } | null = null;
    for (const claim of params.candidateSkills) {
      const edge = findEdge(graph, claim.name, req.skill, "TRANSFERABLE_TO");
      if (edge) {
        transfer = { from: claim.name, edge, via: "edge" };
        break;
      }
      if (!transfer) {
        const ownNode = graph.find((n) => norm(n.skill) === norm(claim.name));
        const reqNode = graph.find((n) => norm(n.skill) === norm(req.skill));
        if (ownNode && reqNode && ownNode.category && ownNode.category === reqNode.category) {
          transfer = { from: claim.name, edge: null, via: `same category (${ownNode.category})` };
        }
      }
    }
    if (transfer) {
      transferableItems.push({
        skill: req.skill,
        classification: "transferable",
        required_proficiency: req.target_proficiency,
        candidate_proficiency: ownProficiency || null,
        edge: transfer.edge
          ? { from_skill: transfer.from, type: "TRANSFERABLE_TO", weight: transfer.edge.weight }
          : null,
        contribution: null,
        reason: transfer.edge
          ? `No direct or adjacent path; ${transfer.from} → ${req.skill} is transferable.`
          : `No direct or adjacent path; ${transfer.from} shares the ${transfer.via}.`,
      });
      continue;
    }

    gapItems.push({
      skill: req.skill,
      classification: "gap",
      required_proficiency: req.target_proficiency,
      candidate_proficiency: ownProficiency || null,
      edge: null,
      contribution: null,
      reason: `No direct, adjacent, or transferable path found for ${req.skill}.`,
    });
  }

  const S_direct =
    directValues.length > 0
      ? directValues.reduce((a, b) => a + b, 0) / directValues.length
      : 0;

  const missing = params.requiredSkills.length - ownedCount; // skills not owned at all
  const S_adjacent =
    missing === 0
      ? 1 // nothing missing to be adjacent to
      : adjacentValues.length > 0
        ? adjacentValues.reduce((a, b) => a + b, 0) / missing
        : 0;

  const artifactCount = params.candidateSkills.filter(
    (s) => s.verification_rigor === "high" || s.verification_rigor === "medium"
  ).length;
  const S_evidence = Math.min(1, artifactCount / threshold);

  const S_seniority = Math.max(0, 1 - 0.2 * Math.abs(params.candidateLevel - params.roleLevel));

  const score =
    MATCH_WEIGHTS.direct * S_direct +
    MATCH_WEIGHTS.adjacent * S_adjacent +
    MATCH_WEIGHTS.evidence * S_evidence +
    MATCH_WEIGHTS.seniority * S_seniority;

  return {
    target_type: params.target.type,
    target_id: params.target.id,
    target_title: params.target.title,
    scenario: params.scenario,
    score: round3(score),
    sections: {
      direct: { value: round3(S_direct), items: directItems },
      adjacent: { value: round3(S_adjacent), items: adjacentItems },
      evidence: { value: round3(S_evidence), artifact_count: artifactCount, threshold },
      seniority: {
        value: round3(S_seniority),
        candidate_level: params.candidateLevel,
        role_level: params.roleLevel,
      },
    },
    classification: {
      direct: directItems,
      adjacent: adjacentItems,
      transferable: transferableItems,
      gaps: gapItems,
    },
    computed_at: params.computedAt ?? new Date().toISOString(),
  };
}

/** Cache key for computed_fits[] entries. */
export function fitKey(record: { target_type: string; target_id: string; scenario: string }) {
  return `${record.target_type}|${record.target_id}|${record.scenario}`;
}


// ---------------------------------------------------------------------------
// WorkSense application stage engine — the single authorized transition matrix.
// Stage moves are enforced server-side; the client never picks a stage freely.
// A transition is allowed only if (role, current_stage, decision) exists in the
// matrix. Stale-state conflicts (expected_stage / expected_version mismatch)
// surface as a typed 409 so the client can refresh instead of clobbering.
// ---------------------------------------------------------------------------

export const STAGE_ORDER = [
  "screening",
  "technical_interview",
  "final_round",
  "selected",
  "rejected",
] as const;

export type ApplicationStage = (typeof STAGE_ORDER)[number];

export type StageDecision = "move_forward" | "reject" | "select";

/** Roles allowed to drive application stage transitions. */
export const STAGE_ACTOR_ROLES = ["hr_executive", "recruiter"] as const;

type MatrixKey = `${ApplicationStage}|${StageDecision}`;

/** Authorized transitions. Rejection is allowed from any open stage; selection
 *  only from the final round; forward movement only along the pipeline. */
const TRANSITION_MATRIX: Partial<Record<MatrixKey, ApplicationStage>> = {
  "screening|move_forward": "technical_interview",
  "technical_interview|move_forward": "final_round",
  "final_round|select": "selected",
  "screening|reject": "rejected",
  "technical_interview|reject": "rejected",
  "final_round|reject": "rejected",
};

export interface TransitionError {
  ok: false;
  code: "INVALID_DECISION" | "STAGE_TERMINAL" | "TRANSITION_DENIED";
  message: string;
}

/** Resolve the target stage for (current_stage, decision) or a typed error. */
export function resolveTransition(
  current: string,
  decision: string
): { ok: true; newStage: ApplicationStage } | TransitionError {
  const from = current as ApplicationStage;
  if (!STAGE_ORDER.includes(from)) {
    return { ok: false, code: "INVALID_DECISION", message: `Unknown stage "${current}".` };
  }
  if (!["move_forward", "reject", "select"].includes(decision)) {
    return { ok: false, code: "INVALID_DECISION", message: `Unknown decision "${decision}".` };
  }
  if (from === "selected" || from === "rejected") {
    return { ok: false, code: "STAGE_TERMINAL", message: `Stage "${from}" is terminal — no further transitions.` };
  }
  const target = TRANSITION_MATRIX[`${from}|${decision}` as MatrixKey];
  if (!target) {
    return {
      ok: false,
      code: "TRANSITION_DENIED",
      message:
        decision === "move_forward" && from === "final_round"
          ? "Candidates in the final round must be selected or rejected."
          : `Decision "${decision}" is not allowed from stage "${from}".`,
    };
  }
  return { ok: true, newStage: target };
}

export interface StaleState {
  stale: boolean;
  currentStage: string;
  currentVersion: number;
}

/** Optimistic-concurrency check: the caller's expectation must match reality. */
export function checkStale(
  expectedStage: string | undefined,
  expectedVersion: number | undefined,
  actualStage: string,
  actualVersion: number
): StaleState {
  const stale =
    (expectedStage !== undefined && expectedStage !== actualStage) ||
    (expectedVersion !== undefined && expectedVersion !== actualVersion);
  return { stale, currentStage: actualStage, currentVersion: actualVersion };
}

export const STAGE_LABELS: Record<ApplicationStage, string> = {
  screening: "Screening",
  technical_interview: "Technical interview",
  final_round: "Final round",
  selected: "Selected",
  rejected: "Rejected",
};


import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";



const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};
const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );

  const authHeader = req.headers.get("Authorization") ?? "";
  const { data: userData } = await supabase.auth.getUser(authHeader.replace("Bearer ", ""));
  const uid = userData?.user?.id;
  if (!uid) return json({ error: "UNAUTHENTICATED" }, 401);

  const { data: caller } = await supabase
    .from("digital_twins")
    .select("id, role, email, org_id")
    .eq("auth_user_id", uid)
    .maybeSingle();
  if (!caller || !STAGE_ACTOR_ROLES.includes(caller.role as (typeof STAGE_ACTOR_ROLES)[number])) {
    return json({ error: "FORBIDDEN", message: "Recruitment access required." }, 403);
  }

  let body: {
    application_id?: string;
    decision?: string;
    reason?: string;
    expected_stage?: string;
    expected_version?: number;
  } = {};
  try {
    body = await req.json();
  } catch {
    /* empty */
  }
  const applicationId = (body.application_id ?? "").trim();
  const decision = body.decision ?? "";
  if (!applicationId || !["move_forward", "reject", "select"].includes(decision)) {
    return json({ error: "VALIDATION_ERROR", message: "application_id and decision (move_forward|reject|select) are required." }, 400);
  }

  const { data: application } = await supabase
    .from("applications")
    .select("*")
    .eq("id", applicationId)
    .eq("org_id", caller.org_id)
    .maybeSingle();
  if (!application) return json({ error: "NOT_FOUND", message: "Application not found." }, 404);

  // Optimistic-concurrency: the caller must agree on stage AND version.
  const stale = checkStale(
    body.expected_stage ?? application.stage,
    body.expected_version ?? application.version,
    application.stage,
    application.version
  );
  if (stale.stale) {
    return json({
      error: "STALE_STATE",
      message: `Application moved since you loaded it (stage "${stale.currentStage}", version ${stale.currentVersion}). Refresh and retry.`,
      current_stage: stale.currentStage,
      current_version: stale.currentVersion,
    }, 409);
  }

  const transition = resolveTransition(application.stage, decision);
  if (transition.ok === false) {
    return json({ error: transition.code, message: transition.message }, transition.code === "STAGE_TERMINAL" ? 409 : 400);
  }
  const newStage = transition.newStage;
  const now = new Date().toISOString();
  const actor = caller.email ?? uid;

  // Select path: atomic conversion (mirrors recruiter-decision) + fit compute.
  let conversion: unknown = null;
  let fits: { current: number | null; future: number | null } = { current: null, future: null };
  if (decision === "select") {
    const { data: conv, error: convErr } = await supabase.rpc("convert_candidate_to_employee", {
      p_twin_id: application.candidate_twin_id,
      p_req_id: application.requisition_id,
    });
    if (convErr) return json({ error: "INTERNAL", message: convErr.message }, 500);
    conversion = conv;

    const { data: reqRow } = await supabase
      .from("job_requisitions")
      .select("id, title, required_skills, future_skills, seniority_level")
      .eq("id", application.requisition_id)
      .maybeSingle();
    const { data: twin } = await supabase
      .from("digital_twins")
      .select("id, org_id, verified_skills, seniority_level, computed_fits, audit_events")
      .eq("id", application.candidate_twin_id)
      .maybeSingle();
    if (reqRow && twin) {
      const { data: graphRows } = await supabase
        .from("skill_graph")
        .select("skill, category, outgoing_edges")
        .eq("org_id", caller.org_id);
      const fitCurrent = computeFit({
        candidateSkills: twin.verified_skills ?? [],
        candidateLevel: twin.seniority_level ?? 3,
        requiredSkills: reqRow.required_skills ?? [],
        roleLevel: reqRow.seniority_level ?? 3,
        skillGraph: graphRows ?? [],
        target: { type: "requisition", id: reqRow.id, title: reqRow.title },
        scenario: "current",
        computedAt: now,
      });
      const fitFuture = computeFit({
        candidateSkills: twin.verified_skills ?? [],
        candidateLevel: twin.seniority_level ?? 3,
        requiredSkills: reqRow.future_skills ?? [],
        roleLevel: reqRow.seniority_level ?? 3,
        skillGraph: graphRows ?? [],
        target: { type: "requisition", id: reqRow.id, title: reqRow.title },
        scenario: "future",
        computedAt: now,
      });
      const prev = (twin.computed_fits ?? []) as { target_id: string; scenario: string }[];
      await supabase
        .from("digital_twins")
        .update({
          computed_fits: [
            ...prev.filter((f) => !(f.target_id === reqRow.id && (f.scenario === "current" || f.scenario === "future"))),
            fitCurrent, fitFuture,
          ],
          audit_events: [
            ...(twin.audit_events ?? []),
            { actor, action: "conversion_fit_computed", note: `Role fit current ${fitCurrent.score.toFixed(2)} / future ${fitFuture.score.toFixed(2)} for ${reqRow.title}.`, timestamp: now },
          ],
        })
        .eq("id", twin.id);
      fits = { current: fitCurrent.score, future: fitFuture.score };
    }
  }

  // Update the authoritative applications row (versioned) + stage event.
  const nextVersion = (application.version ?? 1) + 1;
  const { data: updatedApp, error: appErr } = await supabase
    .from("applications")
    .update({ stage: newStage, version: nextVersion, updated_at: now })
    .eq("id", application.id)
    .eq("version", application.version)
    .select("id, stage, version")
    .single();
  if (appErr) {
    // The version guard should have held; report a conflict rather than clobber.
    const { data: cur } = await supabase.from("applications").select("stage, version").eq("id", application.id).single();
    return json({ error: "STALE_STATE", message: "The application changed concurrently.", current_stage: cur?.stage, current_version: cur?.version }, 409);
  }

  const reason = (body.reason ?? "").trim() || (decision === "move_forward" ? `Advanced to ${newStage.replace(/_/g, " ")}.` : decision === "select" ? "Candidate selected and converted to employee." : "Candidate rejected.");
  const auditRef = `stage:${application.id}:${application.version}`;
  const { error: evErr } = await supabase.from("application_stage_events").insert({
    org_id: caller.org_id,
    application_id: application.id,
    actor_twin_id: caller.id,
    prior_stage: application.stage,
    new_stage: newStage,
    reason,
    at: now,
    version: nextVersion,
    audit_ref: auditRef,
  });
  if (evErr) return json({ error: "INTERNAL", message: evErr.message }, 500);

  // Keep the legacy requisition applicants[] jsonb in sync (stage, code, score).
  const { data: reqRow } = await supabase
    .from("job_requisitions")
    .select("id, applicants, audit_events")
    .eq("id", application.requisition_id)
    .maybeSingle();
  if (reqRow) {
    const applicants = (reqRow.applicants ?? []) as { twin_id: string; stage: string; application_code?: string; match_score?: number | null }[];
    const nextApplicants = applicants.map((a) =>
      a.twin_id === application.candidate_twin_id ? { ...a, stage: newStage, application_code: a.application_code ?? application.application_code } : a
    );
    await supabase
      .from("job_requisitions")
      .update({
        applicants: nextApplicants,
        audit_events: [
          ...(reqRow.audit_events ?? []),
          { actor, action: `applicant_${newStage.replace("_", "_")}`, note: `${reason}`, timestamp: now },
        ],
      })
      .eq("id", reqRow.id);
  }

  const { data: events } = await supabase
    .from("application_stage_events")
    .select("id, prior_stage, new_stage, reason, at, version, actor_twin_id")
    .eq("application_id", application.id)
    .order("at", { ascending: true });

  return json({
    ok: true,
    application: updatedApp,
    decision,
    transition: { prior_stage: application.stage, new_stage: newStage },
    reason,
    version: nextVersion,
    conversion,
    fits,
    history: events ?? [],
  });
});
