// GENERATED by scripts/bundle-functions.mjs — do not edit by hand.
// Edit supabase/functions/_shared/* and <fn>/source.ts, then re-run the bundler.

// ---------------------------------------------------------------------------
// Workforce Review Signal engine — deterministic, zero LLM.
// This is the PS's "Attrition Prediction System" built as decision SUPPORT.
// Internally the field is `risk_score`; every user-facing label says
// "Workforce Review Signal: NN/100 — Multiple workforce indicators warrant
// HR review". Never phrased as a prediction about a person's intent.
// ---------------------------------------------------------------------------

export interface WorkforceSignalInput {
  promotion_lag_months: number; // months in current band without promotion
  promotion_threshold_months?: number; // ~3 years = 36
  attendance: { baseline: number; recent: number }; // unapproved absences / month
  delivery: { missed: number; total: number }; // missed milestones / blocked tasks
  seeks_growth: boolean; // performance-review flag set when seeding, not derived live
}

export interface WorkforceSignalResult {
  risk_score: number; // 0-100, what the UI shows
  signal: number; // 0-1
  factors: { tenure: number; attendance: number; delivery: number; growth: number };
}

// Validated weights — keep the total ≤ 1.0 (0.18 reserved for a future 4th signal).
export const SIGNAL_WEIGHTS = { tenure: 0.28, attendance: 0.2, delivery: 0.22, growth: 0.12 } as const;
export const ATTENDANCE_CAP_RATIO = 2; // doubling absences vs baseline = full factor

export function computeWorkforceSignal(input: WorkforceSignalInput): WorkforceSignalResult {
  const threshold = input.promotion_threshold_months ?? 36;

  // F_tenure: 1 if time-in-band exceeds ~3 years without promotion, scaled otherwise.
  const F_tenure = Math.min(1, Math.max(0, input.promotion_lag_months) / threshold);

  // F_attendance: deviation of RECENT unapproved absence pattern from the
  // person's OWN rolling baseline (pattern change, never cross-person counts).
  const baseline = Math.max(0, input.attendance?.baseline ?? 0);
  const recent = Math.max(0, input.attendance?.recent ?? 0);
  let F_attendance = 0;
  if (baseline <= 0) {
    F_attendance = recent > 0 ? 1 : 0; // any unapproved absence where none existed before
  } else if (recent > baseline) {
    F_attendance = Math.min(1, (recent / baseline - 1) / (ATTENDANCE_CAP_RATIO - 1));
  }

  // F_delivery: recent missed milestones / blocked tasks ratio.
  const total = Math.max(0, input.delivery?.total ?? 0);
  const missed = Math.max(0, Math.min(total, input.delivery?.missed ?? 0));
  const F_delivery = total > 0 ? missed / total : 0;

  // F_growth: seeded flag "seeks more scope/leadership".
  const F_growth = input.seeks_growth ? 1 : 0;

  const signal = Math.min(
    1,
    SIGNAL_WEIGHTS.tenure * F_tenure +
      SIGNAL_WEIGHTS.attendance * F_attendance +
      SIGNAL_WEIGHTS.delivery * F_delivery +
      SIGNAL_WEIGHTS.growth * F_growth
  );

  return {
    risk_score: Math.round(signal * 100),
    signal,
    factors: { tenure: F_tenure, attendance: F_attendance, delivery: F_delivery, growth: F_growth },
  };
}


import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";


const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });

async function isTeamMember(supabase, rootTwinId: string, checkTwinId: string): Promise<boolean> {
  const { data } = await supabase.from("digital_twins").select("id, manager_id");
  const children = new Map<string, string[]>();
  for (const t of data ?? []) {
    if (t.manager_id) children.set(t.manager_id, [...(children.get(t.manager_id) ?? []), t.id]);
  }
  const seen = new Set<string>();
  const stack = [rootTwinId];
  while (stack.length > 0) {
    const cur = stack.pop()!;
    if (seen.has(cur)) continue;
    seen.add(cur);
    for (const c of children.get(cur) ?? []) stack.push(c);
  }
  return seen.has(checkTwinId);
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );

  const authHeader = req.headers.get("Authorization") ?? "";
  const { data: userData } = await supabase.auth.getUser(authHeader.replace("Bearer ", ""));
  const uid = userData?.user?.id;
  if (!uid) return json({ error: "UNAUTHENTICATED" }, 401);

  const { data: caller } = await supabase
    .from("digital_twins")
    .select("id, role, org_id")
    .eq("auth_user_id", uid)
    .maybeSingle();
  if (!caller) return json({ error: "UNAUTHENTICATED" }, 401);

  let body: { twin_id?: string; force?: boolean } = {};
  try {
    body = await req.json();
  } catch {
    /* empty */
  }
  const twinId = (body.twin_id ?? "").trim();
  if (!twinId) return json({ error: "VALIDATION_ERROR", message: "twin_id is required." }, 400);

  const { data: twin, error: twinErr } = await supabase
    .from("digital_twins")
    .select("id, org_id, role, tenure_months, promotion_lag_months, attendance, delivery, signals, audit_events")
    .eq("id", twinId)
    .maybeSingle();
  if (twinErr || !twin) return json({ error: "NOT_FOUND" }, 404);

  let allowed = false;
  if (["hr_executive", "hr_partner"].includes(caller.role)) allowed = twin.org_id === caller.org_id;
  else if (caller.role === "manager" || caller.role === "employee") {
    allowed = twin.id === caller.id || (caller.role === "manager" && (await isTeamMember(supabase, caller.id, twin.id)));
  }
  if (!allowed) return json({ error: "FORBIDDEN" }, 403);

  const signals = (twin.signals ?? []) as { type?: string; value?: unknown }[];
  const seeksGrowth = signals.some((s) => s.type === "seeks_growth" && s.value === true);

  const result = computeWorkforceSignal({
    promotion_lag_months: twin.promotion_lag_months ?? 0,
    attendance: twin.attendance ?? {},
    delivery: twin.delivery ?? {},
    seeks_growth: seeksGrowth,
  });

  const now = new Date().toISOString();
  const nextSignals = signals
    .filter((s) => s.type !== "workforce_review_signal")
    .concat([
      {
        type: "workforce_review_signal",
        value: result.risk_score,
        signal: result.signal,
        computed_at: now,
        factors: result.factors,
        label: "Multiple workforce indicators warrant HR review",
      },
    ]);

  await supabase
    .from("digital_twins")
    .update({
      signals: nextSignals,
      audit_events: [
        ...(twin.audit_events ?? []),
        { actor: caller.id, action: "workforce_signal_computed", note: `Workforce Review Signal recomputed to ${result.risk_score}/100.`, timestamp: now },
      ],
    })
    .eq("id", twinId);

  return json({ ok: true, risk_score: result.risk_score, factors: result.factors, label: "Multiple workforce indicators warrant HR review" });
});
