// GENERATED by scripts/bundle-functions.mjs — do not edit by hand.
// Edit supabase/functions/_shared/* and <fn>/source.ts, then re-run the bundler.

// ---------------------------------------------------------------------------
// WorkSense candidate comparison engine (Phase 4 + audit rework).
// Turns requisition criteria + per-candidate persisted fits + assessment /
// interview signals into comparison rows bucketed by match status.
//
// Audit rework: the comparison is now an EVIDENCE FUNNEL with an explicit,
// deterministic ranking formula:
//   rank = renormalized weighted mean over KNOWN components
//     mandatory readiness (0.35) + preferred readiness (0.20)
//     + work-sample rubric (0.20) + structured-interview rubric (0.15)
//     + evidence confidence (0.10)
// Weights renormalize over whatever components are actually measured — an
// unknown component is never scored as zero. Mandatory gates run BEFORE
// ranking: a candidate with an unmet mandatory requirement is "Gated", never
// ranked. "Insufficient evidence" is its own state when no requirement has any
// direct or adjacent contribution. Ties display a deterministic reason.
// Ranking excludes protected/proxy attributes (name, gender-coded terms, age,
// photo, address, college prestige) — surfaced in the fairness panel.
// ---------------------------------------------------------------------------

export interface ReqCriterionView {
  skill: string;
  target_proficiency: number;
  requirement: "required" | "preferred";
  weight: number;
  evidence_expectation: string;
}

export type MatchStatus = "scored" | "unscored" | "stale";

/** Per-candidate non-fit signals used by the ranking (unknown = null, never 0). */
export interface CandidateSignals {
  /** Reviewed work-sample rubric score (0-1), when one exists. */
  work_sample: number | null;
  work_sample_reviewed: boolean;
  /** Reviewed knowledge-assessment score (0-1), when one exists. */
  knowledge: number | null;
  knowledge_reviewed: boolean;
  /** Structured-interview rubric score (0-1) from the latest round. */
  interview_score: number | null;
  interview_status: "none" | "scheduled" | "scored";
  /** Any candidate session has been submitted for this requisition. */
  assessment_submitted: boolean;
}

export interface CompareRow {
  twin_id: string;
  name: string;
  email: string | null;
  stage: string;
  version: number;
  application_code: string;
  applied_at: string;
  status: MatchStatus;
  score: number | null;
  score_at: string | null;
  gaps: string[];
  adjacent: string[];
  transferable: string[];
  // --- Audit rework: evidence funnel + explainable ranking ---
  /** Mandatory gate (true/false) when a fit exists; null when unscored. */
  gate_met: boolean | null;
  mandatory_readiness: number | null;
  preferred_readiness: number | null;
  verified_coverage: { met: number; total: number };
  provisional_coverage: { met: number; total: number };
  evidence_confidence: number | null;
  work_sample: number | null;
  work_sample_reviewed: boolean;
  interview_score: number | null;
  interview_status: "none" | "scheduled" | "scored";
  assessment_submitted: boolean;
  /** Deterministic explainable rank (0-1) or null when not rankable. */
  rank: number | null;
  rank_components: {
    mandatory: number | null;
    preferred: number | null;
    work_sample: number | null;
    interview: number | null;
    confidence: number | null;
  };
  /** "ranked" | "gated" | "insufficient" | "unranked" */
  rank_tier: "ranked" | "gated" | "insufficient" | "unranked";
  /** Deterministic explanation when two ranked rows tie on the composite. */
  tie_reason: string | null;
}

/** Visible weighting policy for the explainable rank (renormalized over known
 *  components). */
export const RANK_WEIGHTS = {
  mandatory: 0.35,
  preferred: 0.2,
  work_sample: 0.2,
  interview: 0.15,
  confidence: 0.1,
} as const;

export interface CompareInputs {
  req: {
    id: string;
    title: string;
    audit_events: { action?: string; timestamp?: string }[];
    requisition_criteria: ReqCriterionView[];
    required_skills: { skill: string; target_proficiency: number }[];
  };
  applicants: {
    twin_id: string;
    stage: string;
    version?: number;
    application_code: string;
    applied_at: string;
  }[];
  candidates: Map<string, { id: string; name: string; email: string | null }>;
  /** twin_id -> persisted fit for THIS requisition (scenario current). */
  fits: Map<
    string,
    {
      score: number;
      computed_at: string;
      profile_match?: number;
      evidence_confidence?: number;
      mandatory_gate?: { met: boolean; unmet_skills: string[] };
      scoring?: {
        requirements: {
          skill: string;
          relationship: string;
          verified_contribution: number | null;
          contribution: number | null;
        }[];
        mandatory?: { readiness: number | null };
        preferred?: { readiness: number | null } | null;
      };
    }
  >;
  /** twin_id -> non-fit signals (assessments / interviews). */
  signals?: Map<string, CandidateSignals>;
}

export interface CompareResult {
  rows: CompareRow[];
  criteria: ReqCriterionView[];
  scored_count: number;
  unscored_count: number;
  stale_count: number;
  /** Visible weighting policy + fairness panel (audit rework). */
  rank_weights: typeof RANK_WEIGHTS;
  fairness: {
    excluded_attributes: string[];
    statement: string;
  };
}

const EMPTY_SIGNAL: CandidateSignals = {
  work_sample: null,
  work_sample_reviewed: false,
  knowledge: null,
  knowledge_reviewed: false,
  interview_score: null,
  interview_status: "none",
  assessment_submitted: false,
};

const round3 = (n: number) => Math.round(n * 1000) / 1000;

/** Deterministic explainable rank. Returns {rank, tier, reason} — never zeros
 *  for unknowns, never a rank through an unmet mandatory gate. */
function explainableRank(input: {
  gateMet: boolean | null;
  mandatory: number | null;
  preferred: number | null;
  workSample: number | null;
  interview: number | null;
  confidence: number | null;
}): { rank: number | null; tier: CompareRow["rank_tier"]; components: CompareRow["rank_components"] } {
  const components: CompareRow["rank_components"] = {
    mandatory: input.mandatory,
    preferred: input.preferred,
    work_sample: input.workSample,
    interview: input.interview,
    confidence: input.confidence,
  };
  const known = (Object.entries(components) as [keyof typeof RANK_WEIGHTS, number | null][]).filter(([, v]) => v !== null);
  // No fit signal at all -> unscored territory (handled by status).
  if (input.gateMet === null) return { rank: null, tier: "unranked", components };
  if (input.gateMet === false) return { rank: null, tier: "gated", components };
  if (known.length === 0) return { rank: null, tier: "insufficient", components };
  // Insufficient evidence: a fit exists but nothing maps to any requirement.
  const wSum = known.reduce((s, [k]) => s + RANK_WEIGHTS[k], 0);
  const rank = known.reduce((s, [k, v]) => s + RANK_WEIGHTS[k] * (v as number), 0) / wSum;
  return { rank: round3(rank), tier: "ranked", components };
}

export function buildCandidateComparison(inputs: CompareInputs): CompareResult {
  const reqAuditNewest = (inputs.req.audit_events ?? [])
    .map((a) => new Date(a.timestamp ?? 0).getTime())
    .filter((t) => Number.isFinite(t))
    .reduce((max, t) => Math.max(max, t), 0);

  const rows: CompareRow[] = inputs.applicants.map((app) => {
    const cand = inputs.candidates.get(app.twin_id);
    const fit = inputs.fits.get(app.twin_id);
    const signals = inputs.signals?.get(app.twin_id) ?? EMPTY_SIGNAL;
    const requirements = fit?.scoring?.requirements ?? [];
    let status: MatchStatus = "unscored";
    if (fit) {
      const fitAt = new Date(fit.computed_at).getTime();
      status = Number.isFinite(fitAt) && reqAuditNewest > fitAt ? "stale" : "scored";
    }

    const verifiedMet = requirements.filter((r) => (r.verified_contribution ?? 0) > 0).length;
    const provisionalMet = requirements.filter((r) => (r.contribution ?? 0) > 0).length;
    const total = requirements.length;
    const nothingMaps = total > 0 && verifiedMet === 0 && requirements.every((r) => (r.contribution ?? 0) <= 0);

    const rankResult = explainableRank({
      gateMet: fit ? (fit.mandatory_gate?.met ?? true) : null,
      mandatory: fit?.scoring?.mandatory?.readiness ?? null,
      preferred: fit?.scoring?.preferred?.readiness ?? null,
      workSample: signals.work_sample,
      interview: signals.interview_score,
      confidence: fit ? fit.evidence_confidence ?? null : null,
    });

    return {
      twin_id: app.twin_id,
      name: cand?.name ?? "Unknown candidate",
      email: cand?.email ?? null,
      stage: app.stage,
      version: app.version ?? 1,
      application_code: app.application_code,
      applied_at: app.applied_at,
      status,
      score: fit ? fit.score : null,
      score_at: fit ? fit.computed_at : null,
      gaps: requirements.filter((r) => r.relationship === "none").map((g) => g.skill),
      adjacent: requirements.filter((r) => r.relationship === "adjacent").map((g) => g.skill),
      transferable: requirements.filter((r) => r.relationship === "transferable").map((g) => g.skill),
      gate_met: fit ? (fit.mandatory_gate?.met ?? true) : null,
      mandatory_readiness: fit?.scoring?.mandatory?.readiness ?? null,
      preferred_readiness: fit?.scoring?.preferred?.readiness ?? null,
      verified_coverage: { met: verifiedMet, total },
      provisional_coverage: { met: provisionalMet, total },
      evidence_confidence: fit ? fit.evidence_confidence ?? null : null,
      work_sample: signals.work_sample,
      work_sample_reviewed: signals.work_sample_reviewed,
      interview_score: signals.interview_score,
      interview_status: signals.interview_status,
      assessment_submitted: signals.assessment_submitted,
      rank: rankResult.tier === "gated" || nothingMaps ? null : rankResult.rank,
      rank_components: rankResult.components,
      // Gated takes precedence; otherwise nothing mapping to ANY requirement is
      // "insufficient evidence" — a real state, never a zero rank.
      rank_tier: rankResult.tier === "gated" ? "gated" : nothingMaps ? "insufficient" : rankResult.tier,
      tie_reason: null,
    };
  });

  // Bucket + fair ordering: ranked (composite desc) -> gated/insufficient ->
  // unscored -> stale. Ties on the composite get a deterministic reason.
  const scored = rows.filter((r) => r.status === "scored").sort((a, b) => (b.score ?? 0) - (a.score ?? 0));
  const tieIndex = new Map<string, number>();
  let prevRank: number | null = null;
  let prevKey: string | null = null;
  for (const r of scored) {
    if (r.rank === null) continue;
    if (prevRank !== null && Math.abs(r.rank - prevRank) < 1e-9 && prevKey) {
      const a = rows.find((x) => x.twin_id === prevKey);
      if (a) {
        const compDelta = (Object.keys(RANK_WEIGHTS) as (keyof typeof RANK_WEIGHTS)[])
          .map((k) => {
            const diff = (a.rank_components[k] ?? 0) - (r.rank_components[k] ?? 0);
            if (Math.abs(diff) < 1e-9) return null;
            const label = k === "work_sample" ? "work sample" : k;
            return `${diff > 0 ? a.name : r.name} leads on ${label} (+${Math.abs(diff).toFixed(2)})`;
          })
          .filter(Boolean)
          .slice(0, 2)
          .join(" while ");
        r.tie_reason = `Same composite ${r.rank.toFixed(2)} — ${compDelta || "all components are equal to this precision"}.`;
      }
    }
    prevRank = r.rank;
    prevKey = r.twin_id;
  }
  const unscored = rows.filter((r) => r.status === "unscored");
  const stale = rows.filter((r) => r.status === "stale");

  return {
    rows: [...scored, ...unscored, ...stale],
    criteria: inputs.req.requisition_criteria ?? [],
    scored_count: scored.length,
    unscored_count: unscored.length,
    stale_count: stale.length,
    rank_weights: RANK_WEIGHTS,
    fairness: {
      excluded_attributes: [
        "name",
        "gender / gender-coded terms",
        "age and birth year",
        "photo",
        "address and location history",
        "college and institution prestige",
        "any protected or proxy attributes",
      ],
      statement:
        "Ranking uses only evidence and assessment signals: mandatory readiness, preferred readiness, work-sample and interview rubrics, and evidence confidence. Protected or proxy attributes are never read into the composite.",
    },
  };
}


import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";


const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });

/** Normalize rubric judgments (strings or numbers) to a 0-1 mean. Deterministic;
 *  words are ranked by their order in the rubric. Null when no usable judgments. */
function rubricScore(judgments: { judgment?: unknown }[] | undefined | null): number | null {
  const vals = (judgments ?? []).map((j) => j?.judgment).filter((v) => v !== undefined && v !== null);
  if (vals.length === 0) return null;
  const numeric = vals.map((v) => Number(v));
  if (numeric.every((n) => Number.isFinite(n))) {
    const max = Math.max(...numeric, 1);
    return Math.max(0, Math.min(1, numeric.reduce((a, b) => a + b, 0) / numeric.length / max));
  }
  const unique = [...new Set(vals.map((v) => String(v).trim().toLowerCase()))].sort();
  const mean = vals.reduce<number>((s, v) => s + (unique.indexOf(String(v).trim().toLowerCase()) + 1) / unique.length, 0) / vals.length;
  return Math.max(0, Math.min(1, mean));
}

function signalsFor(
  assessments: { twin_id: string; type: string; result?: unknown; reviewed_at?: string | null }[],
  sessions: { twin_id?: string | null; session_type?: string; submitted_at?: string | null }[],
  interviewRubrics: { twin_id: string; rubrics: { role?: string; round?: string; avg_score?: number | null; evaluated_at?: string | null }[] }[]
): Map<string, CandidateSignals> {
  const out = new Map<string, CandidateSignals>();
  const byTwin = new Map<string, CandidateSignals>();

  const merged = (twinId: string) => {
    let s = byTwin.get(twinId);
    if (!s) {
      s = {
        work_sample: null,
        work_sample_reviewed: false,
        knowledge: null,
        knowledge_reviewed: false,
        interview_score: null,
        interview_status: "none",
        assessment_submitted: false,
      };
      byTwin.set(twinId, s);
    }
    return s;
  };

  for (const a of assessments) {
    const s = merged(a.twin_id);
    const result = (a.result ?? {}) as { session_type?: string; ai?: { judgments?: unknown[] }; reviewed?: { judgments?: unknown[] } };
    const judgments = (result.reviewed?.judgments?.length ? result.reviewed.judgments : result.ai?.judgments) as
      | { judgment?: unknown }[]
      | undefined;
    const score = rubricScore(judgments);
    const reviewed = Boolean(a.reviewed_at);
    if (a.type === "work_sample" || result.session_type === "work_sample") {
      s.work_sample = score;
      s.work_sample_reviewed = s.work_sample_reviewed || reviewed;
    } else if (a.type === "knowledge_assessment" || result.session_type === "knowledge_assessment") {
      s.knowledge = score;
      s.knowledge_reviewed = s.knowledge_reviewed || reviewed;
    } else {
      // structured interview assessment
      s.interview_score = score ?? s.interview_score;
      if (score !== null) s.interview_status = "scored";
    }
  }

  for (const sess of sessions) {
    if (!sess.twin_id) continue;
    const s = merged(sess.twin_id);
    if (sess.submitted_at) s.assessment_submitted = true;
  }

  // Interview rubric scores from the twin record (latest round first).
  for (const entry of interviewRubrics) {
    const rubrics = [...(entry.rubrics ?? [])].sort((a, b) => String(b.evaluated_at ?? "").localeCompare(String(a.evaluated_at ?? "")));
    const latest = rubrics[0];
    if (latest && typeof latest.avg_score === "number") {
      const s = merged(entry.twin_id);
      s.interview_score = Math.max(0, Math.min(1, latest.avg_score));
      s.interview_status = "scored";
    }
  }
  for (const [, s] of byTwin) {
    if (s.interview_score === null && s.assessment_submitted) s.interview_status = "scheduled";
  }
  return byTwin;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );

  const authHeader = req.headers.get("Authorization") ?? "";
  const { data: userData } = await supabase.auth.getUser(authHeader.replace("Bearer ", ""));
  const uid = userData?.user?.id;
  if (!uid) return json({ error: "UNAUTHENTICATED" }, 401);

  const { data: caller } = await supabase
    .from("digital_twins")
    .select("id, role, email, org_id")
    .eq("auth_user_id", uid)
    .maybeSingle();
  if (!caller || !["hr_executive", "recruiter"].includes(caller.role)) {
    return json({ error: "FORBIDDEN", message: "Recruitment access required." }, 403);
  }

  let body: { req_id?: string } = {};
  try {
    body = await req.json();
  } catch {
    /* empty */
  }
  const reqId = (body.req_id ?? "").trim();
  if (!reqId) return json({ error: "VALIDATION_ERROR", message: "req_id is required." }, 400);

  const { data: reqRow, error: reqErr } = await supabase
    .from("job_requisitions")
    .select("id, org_id, title, required_skills, future_skills, requisition_criteria, audit_events, applicants")
    .eq("id", reqId)
    .maybeSingle();
  if (reqErr || !reqRow) return json({ error: "NOT_FOUND", message: "Requisition not found." }, 404);
  if (reqRow.org_id !== caller.org_id) return json({ error: "FORBIDDEN" }, 403);

  const applicants = ((reqRow.applicants ?? []) as { twin_id: string; stage: string; application_code: string; applied_at?: string; version?: number }[])
    .map((a) => ({
      twin_id: a.twin_id,
      stage: a.stage,
      version: a.version ?? 1,
      application_code: a.application_code,
      applied_at: a.applied_at ?? "",
    }))
    .filter((a) => a.stage !== "rejected" && a.stage !== "selected");

  // Applications table is the authoritative stage source when present.
  const appRows = applicants.length > 0
    ? await supabase
        .from("applications")
        .select("id, candidate_twin_id, stage, application_code, applied_at, version")
        .eq("requisition_id", reqId)
    : { data: [] as never[] };
  const apps = (appRows.data ?? []) as { id: string; candidate_twin_id: string; stage: string; application_code: string; applied_at: string; version: number }[];
  const appByTwin = new Map(apps.map((a) => [a.candidate_twin_id, a]));

  const twinIds = applicants.map((a) => a.twin_id);
  const { data: twinRows } = twinIds.length > 0
    ? await supabase.from("digital_twins").select("id, name, email, computed_fits, interview_rubrics").in("id", twinIds)
    : { data: [] as never[] };

  // Durable fits first (skill_fits), then legacy computed_fits fallback.
  const { data: storedFits } = twinIds.length > 0
    ? await supabase
        .from("skill_fits")
        .select("twin_id, fit")
        .eq("org_id", caller.org_id)
        .eq("target_type", "requisition")
        .eq("target_id", reqId)
        .eq("scenario", "current")
        .in("twin_id", twinIds)
    : { data: [] as never[] };

  const fits = new Map<string, { score: number; computed_at: string }>();
  for (const s of (storedFits ?? []) as { twin_id: string; fit?: unknown }[]) {
    if (s?.fit) fits.set(s.twin_id, s.fit as { score: number; computed_at: string });
  }
  for (const t of (twinRows ?? []) as { id: string; name: string; email: string | null; computed_fits?: unknown[] }[]) {
    if (fits.has(t.id)) continue;
    const entry = (t.computed_fits ?? []).find(
      (f) =>
        (f as { target_type?: string; target_id?: string; scenario?: string }).target_type === "requisition" &&
        (f as { target_id?: string }).target_id === reqId &&
        (f as { scenario?: string }).scenario === "current"
    );
    if (entry) fits.set(t.id, entry as { score: number; computed_at: string });
  }

  const candidates = new Map(
    ((twinRows ?? []) as { id: string; name: string; email: string | null }[]).map((t) => [t.id, { id: t.id, name: t.name, email: t.email }])
  );

  // ---- Evidence-funnel signals: assessments, candidate sessions, interviews ----
  let signals = new Map<string, CandidateSignals>();
  if (twinIds.length > 0) {
    const appIds = apps.map((a) => a.id);
    const [assessRes, sessRes] = await Promise.all([
      supabase
        .from("assessments")
        .select("id, twin_id, type, result, reviewed_at")
        .eq("org_id", caller.org_id)
        .eq("requisition_id", reqId)
        .in("twin_id", twinIds),
      appIds.length > 0
        ? supabase
            .from("candidate_sessions")
            .select("id, application_id, session_type, submitted_at")
            .eq("org_id", caller.org_id)
            .in("application_id", appIds)
        : Promise.resolve({ data: [] as never[] }),
    ]);
    // candidate_sessions link through application_id -> twin_id.
    const twinByApp = new Map(apps.map((a) => [a.id, a.candidate_twin_id]));
    const sessions = ((sessRes.data ?? []) as { id: string; application_id: string; session_type?: string; submitted_at?: string | null }[])
      .map((s) => ({ twin_id: twinByApp.get(s.application_id) ?? null, session_type: s.session_type, submitted_at: s.submitted_at }));
    const interviewRubrics = (twinRows ?? []).map((t) => ({
      twin_id: t.id,
      rubrics: (((t as { interview_rubrics?: unknown }).interview_rubrics ?? []) as { role?: string; round?: string; avg_score?: number | null; evaluated_at?: string | null }[]),
    }));
    signals = signalsFor(
      (assessRes.data ?? []) as { twin_id: string; type: string; result?: unknown; reviewed_at?: string | null }[],
      sessions,
      interviewRubrics
    );
  }

  const enrichedApplicants = applicants.map((a) => {
    const app = appByTwin.get(a.twin_id);
    return {
      ...a,
      stage: app?.stage ?? a.stage,
      version: app?.version ?? a.version,
      application_code: app?.application_code ?? a.application_code,
      applied_at: app?.applied_at ?? a.applied_at,
    };
  });

  // Audit rework: criteria are rebuilt deterministically from required_skills +
  // future_skills (the canonical source), so mandatory skills are NEVER
  // duplicated as preferred and each section normalizes to a sum of 1.
  // Preferred = FUTURE ADDITIONS only; raised targets stay visible as future
  // capability signals via future_skills, not as duplicate criteria.
  const requiredSkills = (reqRow.required_skills ?? []) as { skill: string; target_proficiency: number }[];
  const futureSkills = (reqRow.future_skills ?? []) as { skill: string; target_proficiency: number }[];
  const requiredSet = new Set(requiredSkills.map((s) => s.skill.toLowerCase()));
  const additions = futureSkills.filter((s) => !requiredSet.has(s.skill.toLowerCase()));
  const nReq = Math.max(requiredSkills.length, 1);
  const nPref = Math.max(additions.length, 1);
  const criteria: ReqCriterionView[] = [
    ...requiredSkills.map((s) => ({
      skill: s.skill,
      target_proficiency: s.target_proficiency,
      requirement: "required" as const,
      weight: Number((1 / nReq).toFixed(2)),
      evidence_expectation: `Source artifact proving ${s.skill} at proficiency ${s.target_proficiency}: prior-role project output, work sample, or verified reference.`,
    })),
    ...additions.map((s) => ({
      skill: s.skill,
      target_proficiency: s.target_proficiency,
      requirement: "preferred" as const,
      weight: Number((1 / nPref).toFixed(2)),
      evidence_expectation: `Evidence of trajectory toward ${s.skill} (learning artifact, stretch work, or certification in progress).`,
    })),
  ];

  const result = buildCandidateComparison({
    req: {
      id: reqRow.id,
      title: reqRow.title,
      audit_events: reqRow.audit_events ?? [],
      requisition_criteria: criteria,
      required_skills: requiredSkills,
    },
    applicants: enrichedApplicants,
    candidates,
    fits,
    signals,
  });

  return json({ ok: true, req_id: reqRow.id, req_title: reqRow.title, ...result });
});
