// GENERATED by scripts/bundle-functions.mjs — do not edit by hand.
// Edit supabase/functions/_shared/* and <fn>/source.ts, then re-run the bundler.

// ---------------------------------------------------------------------------
// WorkSense Qwen client — external OpenAI-compatible endpoint, called ONLY
// from backend functions. The model never computes scores; it only extracts
// structured data / writes rubric text. Resume text is treated as UNTRUSTED
// input: instruction-like phrases are neutralized and the content is wrapped
// in an explicit untrusted delimiter before any model call.
// ---------------------------------------------------------------------------

function getEnv(name: string, fallback: string): string {
  try {
    const deno = (globalThis as { Deno?: { env?: { get?: (n: string) => string | undefined } } }).Deno;
    const fromDeno = deno?.env?.get?.(name);
    if (fromDeno !== undefined) return fromDeno;
  } catch {
    /* node test env */
  }
  try {
    const fromNode = (typeof process !== "undefined" ? process.env?.[name] : undefined) ?? fallback;
    return fromNode;
  } catch {
    return fallback;
  }
}

export const QWEN_BASE_URL = getEnv(
  "QWEN_BASE_URL",
  "https://evolve-eternity-epidural.ngrok-free.dev/v1"
).replace(/\/+$/, "");
export const QWEN_MODEL = getEnv("QWEN_MODEL", "qwen3:4b-instruct-2507-q4_K_M");
export const QWEN_API_KEY = getEnv("QWEN_API_KEY", "local");

// ---------------------------------------------------------------------------
// Untrusted-content handling (resume intake)
// ---------------------------------------------------------------------------

const INSTRUCTION_PATTERNS: RegExp[] = [
  /\bignore\s+(?:(?:all|any|the|your|previous|prior|above|system|developer)\s+)*(?:instructions?|prompts?|rules?|context|messages?|output)\b/gi,
  /\bdisregard\s+(?:(?:all|any|the|your|previous|prior|above|system|developer)\s+)*(?:instructions?|prompts?|rules?|context)\b/gi,
  /\bdo\s+not\s+(?:follow|obey|listen\s+to)\b/gi,
  /\byou\s+are\s+now\b/gi,
  /\bsystem\s+prompt\b/gi,
  /\bdeveloper\s+message\b/gi,
  /\bjailbreak\b/gi,
  /\boverride\s+(?:(?:your|the|system|developer)\s+)*(?:instructions?|rules?|prompt)\b/gi,
  /\bpretend\s+(?:to\s+|that\s+|you\s+)/gi,
  /\bsay\s+you\s+(?:are|have|would|can)\b/gi,
  /\bgive\s+(?:me\s+)?(?:a\s+)?100\s*%?\s*(?:match|fit|score)\b/gi,
  /\balways\s+(?:ignore|follow|obey)\b/gi,
  /\breveal\s+(?:your|the)\s+(?:system|instructions?|prompt)\b/gi,
];

/** Neutralize instruction-like phrases in untrusted resume text. */
export function sanitizeUntrusted(text: string): string {
  let out = String(text ?? "");
  for (const re of INSTRUCTION_PATTERNS) {
    out = out.replace(re, "[redacted]");
  }
  return out.trim();
}

/** Explicit delimiter marking untrusted content for the model. */
export function wrapUntrusted(text: string): string {
  return `<untrusted_input>\n${text}\n</untrusted_input>`;
}

// ---------------------------------------------------------------------------
// OpenAI-compatible chat call
// ---------------------------------------------------------------------------

export class QwenError extends Error {
  constructor(
    public code: "MODEL_UNAVAILABLE" | "MODEL_OUTPUT_INVALID",
    message: string
  ) {
    super(message);
    this.name = "QwenError";
  }
}

function extractJson(content: string): unknown {
  const trimmed = content.trim();
  // Strip markdown fences if present.
  const fenced = trimmed.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "");
  const start = fenced.indexOf("{");
  const end = fenced.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) {
    throw new QwenError("MODEL_OUTPUT_INVALID", `qwen: no JSON object in response: ${content.slice(0, 200)}`);
  }
  try {
    return JSON.parse(fenced.slice(start, end + 1));
  } catch {
    throw new QwenError("MODEL_OUTPUT_INVALID", "qwen: response is not valid JSON.");
  }
}

export async function callQwen(params: {
  system: string;
  user: string;
  json?: boolean;
  maxTokens?: number;
  temperature?: number;
}): Promise<unknown> {
  const body: Record<string, unknown> = {
    model: QWEN_MODEL,
    messages: [
      { role: "system", content: params.system },
      { role: "user", content: params.user },
    ],
    temperature: params.temperature ?? 0.2,
    max_tokens: params.maxTokens ?? 1600,
    stream: false,
  };
  if (params.json) {
    body.response_format = { type: "json_object" };
  }

  let res: Response;
  try {
    res = await fetch(`${QWEN_BASE_URL}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${QWEN_API_KEY}`,
      },
      body: JSON.stringify(body),
    });
  } catch (err) {
    throw new QwenError("MODEL_UNAVAILABLE", `qwen: network error (is the endpoint reachable?): ${err instanceof Error ? err.message : String(err)}`);
  }

  if (!res.ok) {
    const text = await res.text();
    throw new QwenError("MODEL_UNAVAILABLE", `qwen: HTTP ${res.status}: ${text.slice(0, 300)}`);
  }

  const data = await res.json();
  const content = data?.choices?.[0]?.message?.content;
  if (typeof content !== "string" || content.length === 0) {
    throw new QwenError("MODEL_OUTPUT_INVALID", "qwen: empty completion");
  }
  if (params.json) {
    return extractJson(content);
  }
  return content;
}


import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";


const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });

const RUBRIC_SYSTEM = `You are the WorkSense Interview Architect. For the given role and competency, generate one question, two follow-up probes, and a strict 5-tier OBSERVABLE behavioral rubric (concrete behaviors, not adjectives). Tier 1 = concrete red-flag behavior. Tier 3 = solid role-baseline behavior. Tier 5 = master/architectural-level behavior.
Respond with JSON only:
{"competency":"string","question":"string","follow_up_probes":["string","string"],
"rubric":{"tier_1":"string","tier_2":"string","tier_3":"string","tier_4":"string","tier_5":"string"}}`;

const TIER_KEYS = ["tier_1", "tier_2", "tier_3", "tier_4", "tier_5"] as const;

async function generateRubric(supabase, reqRow: { id: string; title: string; required_skills: { skill: string; target_proficiency: number }[] }, competency: string, target: number) {
  const parsed = (await callQwen({
    json: true,
    temperature: 0.3,
    maxTokens: 1200,
    system: RUBRIC_SYSTEM,
    user: `Role: ${reqRow.title}. Competency: ${competency} (required proficiency ${target} of 5).\nProduce the 5-tier behavioral interview rubric as JSON.`,
  })) as {
    competency?: string;
    question?: string;
    follow_up_probes?: string[];
    rubric?: Partial<Record<(typeof TIER_KEYS)[number], string>>;
  };

  return {
    competency: (parsed.competency ?? competency).replace(/\s*\(.*\)\s*$/, "").trim() || competency,
    question: parsed.question ?? `Tell me about your experience with ${competency}.`,
    follow_up_probes: (parsed.follow_up_probes ?? []).slice(0, 2),
    rubric: {
      tier_1: parsed.rubric?.tier_1 ?? "",
      tier_2: parsed.rubric?.tier_2 ?? "",
      tier_3: parsed.rubric?.tier_3 ?? "",
      tier_4: parsed.rubric?.tier_4 ?? "",
      tier_5: parsed.rubric?.tier_5 ?? "",
    },
  };
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  try {

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );

  const authHeader = req.headers.get("Authorization") ?? "";
  const { data: userData } = await supabase.auth.getUser(authHeader.replace("Bearer ", ""));
  const uid = userData?.user?.id;
  if (!uid) return json({ error: "UNAUTHENTICATED" }, 401);

  const { data: caller } = await supabase
    .from("digital_twins")
    .select("id, role, org_id")
    .eq("auth_user_id", uid)
    .maybeSingle();
  if (!caller || !["hr_executive", "recruiter"].includes(caller.role)) {
    return json({ error: "FORBIDDEN", message: "Recruitment access required." }, 403);
  }

  let body: { req_id?: string; competencies?: string[] } = {};
  try {
    body = await req.json();
  } catch {
    /* empty */
  }
  const reqId = (body.req_id ?? "").trim();
  if (!reqId) return json({ error: "VALIDATION_ERROR", message: "req_id is required." }, 400);

  const { data: reqRow, error: reqErr } = await supabase
    .from("job_requisitions")
    .select("id, org_id, title, required_skills, rubrics, audit_events")
    .eq("id", reqId)
    .maybeSingle();
  if (reqErr || !reqRow) return json({ error: "NOT_FOUND", message: "Requisition not found." }, 404);
  if (reqRow.org_id !== caller.org_id) return json({ error: "FORBIDDEN" }, 403);

  const required = (reqRow.required_skills ?? []) as { skill: string; target_proficiency: number }[];
  const wanted = (body.competencies?.length ? body.competencies : [...required.map((r) => r.skill), "Collaboration"]);

  const existing = (reqRow.rubrics ?? []) as { competency: string }[];
  const have = new Set(existing.map((r) => r.competency.toLowerCase()));
  const rubrics = [...existing];

  for (const comp of wanted) {
    const target = required.find((r) => r.skill.toLowerCase() === comp.toLowerCase())?.target_proficiency ?? 3;
    if (have.has(comp.toLowerCase())) continue; // cached — reuse, don't regenerate per candidate
    const rubric = await generateRubric(supabase, reqRow, comp, target);
    const name = rubric.competency.toLowerCase();
    if (have.has(name)) {
      // Replace the stale/badly-named entry rather than duplicate.
      const i = rubrics.findIndex((r) => r.competency.toLowerCase() === name);
      rubrics[i] = rubric;
    } else {
      rubrics.push(rubric);
    }
    have.add(name);
  }

  const now = new Date().toISOString();
  await supabase
    .from("job_requisitions")
    .update({
      rubrics,
      audit_events: [
        ...(reqRow.audit_events ?? []),
        { actor: caller.id, action: "rubrics_generated", note: `Cached ${wanted.length} competency rubrics for ${reqRow.title}.`, timestamp: now },
      ],
    })
    .eq("id", reqId);

  return json({ ok: true, rubrics });
  } catch (err) {
    return json({ error: err instanceof QwenError ? err.code : "INTERNAL", message: err instanceof Error ? err.message : "unknown" });
  }
});