// GENERATED by scripts/bundle-functions.mjs — do not edit by hand.
// Edit supabase/functions/_shared/* and <fn>/source.ts, then re-run the bundler.

// Batch F (F1): authorized overview search for HR and managers.
// Scope is decided SERVER-side from the caller's role — HR searches the org,
// managers only their own reporting subtree. Candidate and requisition groups
// are returned only to HR roles (item 29: a manager can never pull the wider
// org or candidate pipeline). Results are bounded per group. Actions/module
// links are static UI navigation, so they are assembled client-side from the
// same RBAC-driven navigation the app shell uses.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};
const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });

const norm = (s: unknown) => String(s ?? "").trim().toLowerCase();
const has = (fields: (string | null | undefined)[], q: string) => fields.some((f) => f && norm(f).includes(q));

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
  const authHeader = req.headers.get("Authorization") ?? "";
  const { data: userData } = await supabase.auth.getUser(authHeader.replace("Bearer ", ""));
  const uid = userData?.user?.id;
  if (!uid) return json({ error: "UNAUTHENTICATED" }, 401);

  const { data: caller } = await supabase
    .from("digital_twins")
    .select("id, role, org_id")
    .eq("auth_user_id", uid)
    .maybeSingle();
  if (!caller) return json({ error: "UNAUTHENTICATED" }, 401);

  let scope: "org" | "team";
  if (["hr_executive", "hr_partner"].includes(caller.role)) scope = "org";
  else if (caller.role === "manager") scope = "team";
  else return json({ error: "FORBIDDEN", message: "Overview search requires HR or Manager access." }, 403);

  let body: Record<string, unknown> = {};
  try { body = await req.json(); } catch { /* empty */ }
  const q = String(body.q ?? "").trim().toLowerCase();
  if (q.length < 2) {
    return json({ ok: true, q, scope, people: [], candidates: [], roles: [] });
  }

  const { data: allTwins } = await supabase
    .from("digital_twins")
    .select("id, name, role, status, job_title, department, manager_id")
    .eq("org_id", caller.org_id);

  // Manager scope: the caller's reporting subtree only (same BFS the staffing
  // planner and dashboard use).
  let teamIds: Set<string> | null = null;
  if (scope === "team") {
    const children = new Map<string, string[]>();
    for (const t of allTwins ?? []) {
      if (t.manager_id) children.set(t.manager_id, [...(children.get(t.manager_id) ?? []), t.id]);
    }
    teamIds = new Set<string>();
    const stack = [caller.id];
    while (stack.length > 0) {
      const cur = stack.pop()!;
      if (teamIds.has(cur)) continue;
      teamIds.add(cur);
      for (const c of children.get(cur) ?? []) stack.push(c);
    }
  }

  const inScope = (t: { id: string }) => (teamIds ? teamIds.has(t.id) : true);

  // People — active workers in scope matching name, job title or department.
  const people = (allTwins ?? [])
    .filter((t) => t.status === "active" && ["employee", "manager"].includes(t.role) && inScope(t))
    .filter((t) => has([t.name, t.job_title, t.department], q))
    .slice(0, 5)
    .map((t) => ({ id: t.id, name: t.name, job_title: t.job_title ?? null, department: t.department ?? null, role: t.role }));

  // Candidates + requisitions: HR roles only (managers stay scoped out).
  let candidates: { id: string; name: string; department: string | null }[] = [];
  let roles: { id: string; title: string; department: string | null; status: string }[] = [];
  if (["hr_executive", "hr_partner"].includes(caller.role)) {
    candidates = (allTwins ?? [])
      .filter((t) => t.role === "candidate" && has([t.name], q))
      .slice(0, 5)
      .map((t) => ({ id: t.id, name: t.name, department: t.department ?? null }));

    const { data: reqs } = await supabase
      .from("job_requisitions")
      .select("id, title, department, status")
      .eq("org_id", caller.org_id);
    roles = (reqs ?? [])
      .filter((r) => has([r.title, r.department], q))
      .slice(0, 5)
      .map((r) => ({ id: r.id, title: r.title, department: r.department ?? null, status: r.status }));
  }

  return json({ ok: true, q, scope, people, candidates, roles });
});
