import { describe, expect, it } from "vitest";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  computeFit,
  fitKey,
  type FitRecord,
  type GraphSkill,
  type RequiredSkill,
  type SkillClaim,
} from "../supabase/functions/_shared/skill-graph-engine.ts";
import { REQUISITIONS, SKILLS, TWINS } from "../supabase/functions/_shared/seed-data.ts";

const GRAPH = SKILLS as GraphSkill[];

const SEED_PAIRS: { twinId: string; reqId: string; scenario: "current" | "future" }[] = [
  { twinId: "22222222-2222-2222-2222-222222222203", reqId: "33333333-3333-3333-3333-333333333301", scenario: "current" },
  { twinId: "22222222-2222-2222-2222-222222222203", reqId: "33333333-3333-3333-3333-333333333301", scenario: "future" },
  { twinId: "22222222-2222-2222-2222-222222222204", reqId: "33333333-3333-3333-3333-333333333302", scenario: "current" },
  { twinId: "22222222-2222-2222-2222-222222222205", reqId: "33333333-3333-3333-3333-333333333301", scenario: "current" },
  { twinId: "22222222-2222-2222-2222-222222222206", reqId: "33333333-3333-3333-3333-333333333301", scenario: "current" },
  { twinId: "22222222-2222-2222-2222-222222222207", reqId: "33333333-3333-3333-3333-333333333302", scenario: "current" },
];

describe("generate seed fits (offline, deterministic)", () => {
  it("writes generated-seed-fits.ts from the engine", () => {
    const fitsByTwin: Record<string, FitRecord[]> = {};
    for (const p of SEED_PAIRS) {
      const twin = TWINS.find((t) => t.id === p.twinId);
      const req = REQUISITIONS.find((r) => r.id === p.reqId);
      if (!twin || !req) throw new Error(`seed pair missing: ${JSON.stringify(p)}`);

      const skills = (p.scenario === "future" ? req.future_skills : req.required_skills) as RequiredSkill[];
      const fit = computeFit({
        candidateSkills: twin.verified_skills as SkillClaim[],
        candidateLevel: twin.seniority_level,
        requiredSkills: skills,
        roleLevel: req.seniority_level,
        skillGraph: GRAPH,
        target: { type: "requisition", id: req.id, title: req.title },
        scenario: p.scenario,
        computedAt: "2026-09-15T09:00:00Z",
      });
      fitsByTwin[twin.id] = [...(fitsByTwin[twin.id] ?? []), fit];
    }

    const dest = fileURLToPath(new URL("../supabase/functions/_shared/generated-seed-fits.ts", import.meta.url));
    const body = JSON.stringify(fitsByTwin, null, 2);
    const content = `// Auto-generated by scripts/generate-seed-fits.test.ts — do not edit by hand.\n// Produced by the deterministic Skill Intelligence Graph engine from seed-data.ts.\nimport type { FitRecord } from "./skill-graph-engine.ts";\n\nexport const SEED_FITS: Record<string, FitRecord[]> = ${body};\n`;
    writeFileSync(dest, content);

    // Self-check: every fit has a score in [0,1] and is unique per
    // (twin, target_type, target_id, scenario).
    const keys = new Set<string>();
    for (const [twinId, fits] of Object.entries(fitsByTwin)) {
      for (const f of fits) {
        expect(f.score).toBeGreaterThanOrEqual(0);
        expect(f.score).toBeLessThanOrEqual(1);
        keys.add(`${twinId}|${fitKey(f)}`);
      }
    }
    expect(keys.size).toBe(SEED_PAIRS.length);
  });
});
