import { describe, expect, it } from "vitest";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { schedulePlan, type TaskInput } from "../supabase/functions/_shared/onboarding-engine.ts";
import { REQUISITIONS, TWINS } from "../supabase/functions/_shared/seed-data.ts";

const norm = (s: string) => s.trim().toLowerCase().replace(/[^a-z0-9]+/g, "_");

const CORE_TASKS: TaskInput[] = [
  { id: "it", title: "IT & Laptop Provisioning", depends_on: [], duration_days: 1 },
  { id: "security", title: "Security & Compliance Training", depends_on: [], non_waivable: true, duration_days: 1 },
  { id: "payroll", title: "Direct Deposit & Payroll Setup", depends_on: [], non_waivable: true, duration_days: 0.5 },
  { id: "access", title: "System Access & SSO", depends_on: ["it", "security"], duration_days: 0.5 },
  { id: "compliance_signoff", title: "Compliance Sign-off", depends_on: ["security"], non_waivable: true, duration_days: 0.5 },
  { id: "team_intro", title: "Team Introduction & Codebase Walkthrough", depends_on: ["access"], duration_days: 1 },
];

describe("generate seed journey (offline, deterministic)", () => {
  it("writes generated-seed-journey.ts from the engine", () => {
    const alex = TWINS.find((t) => t.id === "22222222-2222-2222-2222-222222222203")!;
    const req = REQUISITIONS.find((r) => r.title === "Senior Backend Engineer")!;

    const tasks: TaskInput[] = [...CORE_TASKS];
    const required = req.required_skills.slice(0, 3);
    const future = req.future_skills.slice(0, 2);
    const firstSkillId = required.length > 0 ? `skill_${norm(required[0].skill)}` : "team_intro";
    for (const s of required) {
      tasks.push({ id: `skill_${norm(s.skill)}`, title: `First contribution using ${s.skill}`, skill: s.skill, target_proficiency: s.target_proficiency, depends_on: ["team_intro"], duration_days: 1 });
    }
    for (const s of future) {
      tasks.push({ id: `future_${norm(s.skill)}`, title: `Upskilling plan: ${s.skill}`, skill: s.skill, target_proficiency: s.target_proficiency, depends_on: [firstSkillId], duration_days: 1 });
    }
    tasks.push({ id: "survey", title: "Onboarding Feedback Survey", depends_on: [firstSkillId], duration_days: 0.5 });

    const scheduled = schedulePlan({
      tasks,
      skills: alex.verified_skills as { name: string; proficiency: number }[],
      startDate: "2026-07-21T09:00:00Z",
      // Mid-onboarding persona: IT, security and team intro already done.
      doneTaskIds: ["it", "security", "team_intro"],
    });

    expect(scheduled.length).toBe(12);
    expect(scheduled.filter((t) => t.status === "done").length).toBe(3);
    expect(scheduled.every((t) => typeof t.topological_level === "number")).toBe(true);
    expect(scheduled.every((t) => t.start_date !== null)).toBe(true);

    const dest = fileURLToPath(new URL("../supabase/functions/_shared/generated-seed-journey.ts", import.meta.url));
    // Self-contained legacy task row: the reset-demo bundle inlines this file
    // and must not import from onboarding-engine (which collides with
    // onboarding-v2 when concatenated). The type is reproduced structurally.
    const content = `// Auto-generated by scripts/generate-seed-journey.test.ts — do not edit by hand.\n// Produced by the deterministic Kahn onboarding engine from seed-data.ts.\ninterface ScheduledTask {\n  id: string;\n  title: string;\n  depends_on: string[];\n  skill?: string;\n  target_proficiency?: number;\n  non_waivable?: boolean;\n  duration_days: number;\n  waived: boolean;\n  status: "waived" | "pending" | "done" | "blocked";\n  start_date: string | null;\n  end_date: string | null;\n  topological_level: number;\n  blocked?: { note: string; reported_by: string; at: string } | null;\n}\n\nexport const SEED_JOURNEY_TASKS: ScheduledTask[] = ${JSON.stringify(scheduled, null, 2)};\n`;
    writeFileSync(dest, content);
  });
});
